// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'adobe-after-effects/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 7v10a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 13v-1a2 2 0 0 1 2-2v0a2 2 0 0 1 2 2v1h-4Zm0 0v1a2 2 0 0 0 2 2h1.5M6 16l1.125-3M12 16l-1.125-3m-3.75 0L9 8l1.875 5m-3.75 0h3.75"/></svg>`
)

export function AdobeAfterEffects(props: IconProps) {
  return <Icon name={name} {...props} />
}

AdobeAfterEffects.prototype.name = name
