// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'at-sign/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17.5 19.125A9 9 0 1 1 21 12c0 5.5-6 5.5-6 2V8"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 12v-1.5C15 9.12 13.657 8 12 8s-3 1.12-3 2.5V12m6 0v1.5c0 1.38-1.343 2.5-3 2.5s-3-1.12-3-2.5V12"/></svg>`
)

export function AtSign(props: IconProps) {
  return <Icon name={name} {...props} />
}

AtSign.prototype.name = name
