// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'backward-15-seconds/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 13a9 9 0 1 0 9-9M9 9v7"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 9h-2a1 1 0 0 0-1 1v1.5a1 1 0 0 0 1 1h1a1 1 0 0 1 1 1V15a1 1 0 0 1-1 1h-2m0-12H4.5m0 0 2-2m-2 2 2 2"/></svg>`
)

export function Backward15Seconds(props: IconProps) {
  return <Icon name={name} {...props} />
}

Backward15Seconds.prototype.name = name
