// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'basketball/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Zm0 0V2"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21.95 11c-6.47 2.667-12.254 2.667-19.9 0"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18.572 4.462c-2.667 4.53-2.667 9.723 0 15.076M5.428 4.462c2.667 4.53 2.667 9.723 0 15.076"/></svg>`
)

export function Basketball(props: IconProps) {
  return <Icon name={name} {...props} />
}

Basketball.prototype.name = name
