// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'book/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" d="M4 19V5a2 2 0 0 1 2-2h13.4a.6.6 0 0 1 .6.6v13.114M6 17h14M6 21h14"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 21a2 2 0 1 1 0-4"/><path stroke="currentColor" stroke-linecap="round" d="M9 7h6"/></svg>`
)

export function Book(props: IconProps) {
  return <Icon name={name} {...props} />
}

Book.prototype.name = name
