// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'bowling-ball/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Z"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11.5 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm-4 3a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm4 2a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z"/></svg>`
)

export function BowlingBall(props: IconProps) {
  return <Icon name={name} {...props} />
}

BowlingBall.prototype.name = name
