// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'codepen/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 9v6M3 15V9m9 12v-6m0-12v6m0 6L3 9l9-6 9 6-9 6Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m12 21-9-6 9-6 9 6-9 6Z"/></svg>`
)

export function Codepen(props: IconProps) {
  return <Icon name={name} {...props} />
}

Codepen.prototype.name = name
