// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'database-settings/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 6v6s0 3 7 3 7-3 7-3V6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 3c7 0 7 3 7 3s0 3-7 3-7-3-7-3 0-3 7-3Zm0 18c-7 0-7-3-7-3v-6m15 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/><path stroke="currentColor" stroke-dasharray="0.3 2" stroke-linecap="round" stroke-linejoin="round" d="M19 22a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/></svg>`
)

export function DatabaseSettings(props: IconProps) {
  return <Icon name={name} {...props} />
}

DatabaseSettings.prototype.name = name
