// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'data-transfer-both/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 20V4m0 0 3 3m-3-3-3 3M7 4v16m0 0 3-3m-3 3-3-3"/></svg>`
)

export function DataTransferBoth(props: IconProps) {
  return <Icon name={name} {...props} />
}

DataTransferBoth.prototype.name = name
