// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'db-search/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20.5 20.5 22 22m-6-3.5a2.5 2.5 0 1 0 5 0 2.5 2.5 0 0 0-5 0ZM4 6v6s0 3 7 3 7-3 7-3V6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 3c7 0 7 3 7 3s0 3-7 3-7-3-7-3 0-3 7-3Zm0 18c-7 0-7-3-7-3v-6"/></svg>`
)

export function DbSearch(props: IconProps) {
  return <Icon name={name} {...props} />
}

DbSearch.prototype.name = name
