// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'doc-search/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20.5 20.5 22 22m-7-4a3 3 0 1 0 6 0 3 3 0 0 0-6 0Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 12V5.749a.6.6 0 0 0-.176-.425l-3.148-3.148A.6.6 0 0 0 16.252 2H4.6a.6.6 0 0 0-.6.6v18.8a.6.6 0 0 0 .6.6H11"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 2v3.4a.6.6 0 0 0 .6.6H20"/></svg>`
)

export function DocSearch(props: IconProps) {
  return <Icon name={name} {...props} />
}

DocSearch.prototype.name = name
