// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'doc-search-alt/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m14 15 1.5 1.5m-7-4a3 3 0 1 0 6 0 3 3 0 0 0-6 0Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 21.4V2.6a.6.6 0 0 1 .6-.6h11.652a.6.6 0 0 1 .424.176l3.148 3.148A.6.6 0 0 1 20 5.75V21.4a.6.6 0 0 1-.6.6H4.6a.6.6 0 0 1-.6-.6Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 2v3.4a.6.6 0 0 0 .6.6H20"/></svg>`
)

export function DocSearchAlt(props: IconProps) {
  return <Icon name={name} {...props} />
}

DocSearchAlt.prototype.name = name
