// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'facebook-tag/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 8v8a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V8a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 21v-9c0-2.188.5-4 4-4m-6 5h6"/></svg>`
)

export function FacebookTag(props: IconProps) {
  return <Icon name={name} {...props} />
}

FacebookTag.prototype.name = name
