// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'fillet-3d/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 20v-4C2 8.268 8.268 2 16 2h4m.839 18.84h-3.536m3.536 0v-3.537m0 3.536L18 18"/><path stroke="currentColor" stroke-dasharray="2 3" stroke-linecap="round" stroke-linejoin="round" d="m9 9 7 7"/></svg>`
)

export function Fillet3D(props: IconProps) {
  return <Icon name={name} {...props} />
}

Fillet3D.prototype.name = name
