// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'glasses/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 14a4 4 0 1 0 8 0 4 4 0 0 0-8 0Zm0 0V6m20 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0Zm0 0V6m-8 8h-4"/></svg>`
)

export function Glasses(props: IconProps) {
  return <Icon name={name} {...props} />
}

Glasses.prototype.name = name
