// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'home-temperature-out/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 8 4.311 3.156a.6.6 0 0 0-.6.037L2.5 4m9.5 7v8a2 2 0 0 1-2 2H7m0 0H3.6a.6.6 0 0 1-.6-.6v-4.8a.6.6 0 0 1 .6-.6h2.8a.6.6 0 0 1 .6.6V21Zm12-3a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0-10.5V14m0-2h2m-2-3h2"/></svg>`
)

export function HomeTemperatureOut(props: IconProps) {
  return <Icon name={name} {...props} />
}

HomeTemperatureOut.prototype.name = name
