// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'intersect-alt/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m15.01 3-.01.011M11.01 3l-.01.011M7.01 3 7 3.011M3.01 3 3 3.011M3.01 7 3 7.011M3.01 11l-.01.011M3.01 15l-.01.011m6 5.999.01-.011m3.99.011.01-.011m3.99.011.01-.011m3.99.011.01-.011M21 17.01l.01-.011M21 13.01l.01-.011M21 9.01l.01-.011M9 17v-7a1 1 0 0 1 1-1h7"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 7v7a1 1 0 0 1-1 1H7"/></svg>`
)

export function IntersectAlt(props: IconProps) {
  return <Icon name={name} {...props} />
}

IntersectAlt.prototype.name = name
