// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'litecoin-rotate-out/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21.168 8A10.003 10.003 0 0 0 12 2c-5.185 0-9.45 3.947-9.95 9"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 8h3.4a.6.6 0 0 0 .6-.6V4M2.881 16c1.544 3.532 5.068 6 9.168 6 5.186 0 9.45-3.947 9.951-9"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.05 16h-3.4a.6.6 0 0 0-.6.6V20"/><path stroke="currentColor" stroke-linecap="round" d="M10.5 7v9.4a.6.6 0 0 0 .6.6h4.4"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m8.5 13 4.5-2"/></svg>`
)

export function LitecoinRotateOut(props: IconProps) {
  return <Icon name={name} {...props} />
}

LitecoinRotateOut.prototype.name = name
