// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'litecoin-circle/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" d="M10.5 7v9.4a.6.6 0 0 0 .6.6h4.4"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m8.5 13 4.5-2m-1 11C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10Z"/></svg>`
)

export function LitecoinCircle(props: IconProps) {
  return <Icon name={name} {...props} />
}

LitecoinCircle.prototype.name = name
