// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'long-arrow-right-up-1/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15.5 7v6a4 4 0 0 1-4 4h-7m11-10 3.5 3.5M15.5 7 12 10.5"/></svg>`
)

export function LongArrowRightUp1(props: IconProps) {
  return <Icon name={name} {...props} />
}

LongArrowRightUp1.prototype.name = name
