// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'more-vert/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 12.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm0 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm0-16a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z"/></svg>`
)

export function MoreVert(props: IconProps) {
  return <Icon name={name} {...props} />
}

MoreVert.prototype.name = name
