// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'mouse-button-right/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" d="M4 10v4a8 8 0 1 0 16 0V9a7 7 0 0 0-7-7h-1a8 8 0 0 0-8 8Z"/><path stroke="currentColor" stroke-linecap="round" d="M12 2v6.4a.6.6 0 0 0 .6.6H20"/></svg>`
)

export function MouseButtonRight(props: IconProps) {
  return <Icon name={name} {...props} />
}

MouseButtonRight.prototype.name = name
