// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'multiple-pages/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7 18h7m-7-4h1m-1-4h3M7 2h9.5L21 6.5V19"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 20.5v-14A1.5 1.5 0 0 1 4.5 5h9.752a.6.6 0 0 1 .424.176l3.148 3.148A.6.6 0 0 1 18 8.75V20.5a1.5 1.5 0 0 1-1.5 1.5h-12A1.5 1.5 0 0 1 3 20.5Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 5v3.4a.6.6 0 0 0 .6.6H18"/></svg>`
)

export function MultiplePages(props: IconProps) {
  return <Icon name={name} {...props} />
}

MultiplePages.prototype.name = name
