// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'numbered-list-left/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9 5h12M5 7V3L3.5 4.5m2 9.5h-2l1.905-2.963a.428.428 0 0 0 .072-.323C5.42 10.456 5.216 10 4.5 10c-1 0-1 .889-1 .889s0 0 0 0v.222M4 19h.5a1 1 0 0 1 1 1v0a1 1 0 0 1-1 1h-1m0-4h2L4 19m5-7h12M9 19h12"/></svg>`
)

export function NumberedListLeft(props: IconProps) {
  return <Icon name={name} {...props} />
}

NumberedListLeft.prototype.name = name
