// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'pen-tablet/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M22 5v14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2ZM2 12h4m0-9v18"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m15.5 11.5-3.5 3m5-4.49.01-.011"/></svg>`
)

export function PenTablet(props: IconProps) {
  return <Icon name={name} {...props} />
}

PenTablet.prototype.name = name
