// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'safe-open/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M3 19V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path stroke="currentColor" d="M13 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7.5 15C6.672 15 6 13.657 6 12s.672-3 1.5-3S9 10.343 9 12s-.672 3-1.5 3Zm5.5-1v-4m-4.5-.5 1-1m-3 1-1-1m0 7 1-1m3 1-1-1M2 8h1M2 6h1m0 10H2m1 2H2"/></svg>`
)

export function SafeOpen(props: IconProps) {
  return <Icon name={name} {...props} />
}

SafeOpen.prototype.name = name
