// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'skateboard/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.5 16a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3ZM2 9l3.333 1h13.334L22 9m-4.5 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"/></svg>`
)

export function Skateboard(props: IconProps) {
  return <Icon name={name} {...props} />
}

Skateboard.prototype.name = name
