// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'stat-up/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 20v-8m0 0 3 3m-3-3-3 3m-9-1 8-8 3 3 5-5"/></svg>`
)

export function StatUp(props: IconProps) {
  return <Icon name={name} {...props} />
}

StatUp.prototype.name = name
