// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'time-zone/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12s4.477 10 10 10"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M13 2.05S16 6 16 12m-5 9.95S8 18 8 12c0-6 3-9.95 3-9.95M2.63 15.5H12m-9.37-7h18.74m-2.37 9V19h1.5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19 23a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"/></svg>`
)

export function TimeZone(props: IconProps) {
  return <Icon name={name} {...props} />
}

TimeZone.prototype.name = name
