// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'xray-view/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 7.353v9.294a.6.6 0 0 1-.309.525l-8.4 4.666a.6.6 0 0 1-.582 0l-8.4-4.666A.6.6 0 0 1 3 16.647V7.353a.6.6 0 0 1 .309-.524l8.4-4.667a.6.6 0 0 1 .582 0l8.4 4.667a.6.6 0 0 1 .309.524Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m20.5 16.722-8.209-4.56a.6.6 0 0 0-.582 0L3.5 16.722m.028-9.428 8.18 4.544a.6.6 0 0 0 .583 0l8.209-4.56M12 21V3"/></svg>`
)

export function XrayView(props: IconProps) {
  return <Icon name={name} {...props} />
}

XrayView.prototype.name = name
