---
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
plugins: ['prettier-plugin-tailwindcss', '@ianvs/prettier-plugin-sort-imports']
importOrder:
  [
    '',
    '^(react/(.*)$)|^(react$)|^(react-dom(.*)$)|^react-(.*)',
    '',
    '<BUILTIN_MODULES>',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '@harnessio(.*)$',
    '',
    '^[.]'
  ]
importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy']
importOrderTypeScriptVersion: '5.0.0'
importOrderCaseSensitive: false
