export declare const box: string
export declare const contentLayer: string
export declare const cardBg: string
export declare const diagnose: string
export declare const glow: string
export declare const gradientBorder: string
export declare const gradientBorderGlow: string
export declare const gradientBorderGray: string
export declare const icon: string
export declare const label: string
export declare const main: string
export declare const marginTop: string
export declare const selected: string
export declare const skeletonIcon: string
export declare const skeletonLine: string
export declare const skeletonLine1: string
export declare const skeletonLine2: string
export declare const skeletonSquare: string
