/**
 * Harness Design System
 * Generated style tokens - DO NOT EDIT DIRECTLY
 * Copyright (c) Harness.
 */

export default {
  component: {
    "markdown-editor": {
      title: {
        h1: {
          $type: "typography",
          $value: "600 1.875rem/2.8125rem Inter",
          $description: "Article main heading.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.600}",
              fontSize: "{fontSize.7}",
              lineHeight: "{lineHeight.7.normal}",
              letterSpacing: "{tracking.tight}",
            },
            $description: "Article main heading.",
          },
          name: "cn-component-markdown-editor-title-h1",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "title",
            subitem: "h1",
          },
          path: ["component", "markdown-editor", "title", "h1"],
        },
        h2: {
          $type: "typography",
          $value: "600 1.5rem/2.25rem Inter",
          $description: "Article section heading.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.600}",
              fontSize: "{fontSize.6}",
              lineHeight: "{lineHeight.6.normal}",
              letterSpacing: "{tracking.tight}",
            },
            $description: "Article section heading.",
          },
          name: "cn-component-markdown-editor-title-h2",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "title",
            subitem: "h2",
          },
          path: ["component", "markdown-editor", "title", "h2"],
        },
        h3: {
          $type: "typography",
          $value: "600 1rem/1.5rem Inter",
          $description: "Article subsection heading.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.600}",
              fontSize: "{fontSize.3}",
              lineHeight: "{lineHeight.3.normal}",
              letterSpacing: "{tracking.normal}",
            },
            $description: "Article subsection heading.",
          },
          name: "cn-component-markdown-editor-title-h3",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "title",
            subitem: "h3",
          },
          path: ["component", "markdown-editor", "title", "h3"],
        },
      },
      content: {
        lead: {
          $type: "typography",
          $value: "400 1.25rem/1.875rem Inter",
          $description: "Article introduction paragraph.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.400}",
              fontSize: "{fontSize.5}",
              lineHeight: "{lineHeight.5.normal}",
              letterSpacing: "{tracking.tight}",
            },
            $description: "Article introduction paragraph.",
          },
          name: "cn-component-markdown-editor-content-lead",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "content",
            subitem: "lead",
          },
          path: ["component", "markdown-editor", "content", "lead"],
        },
        paragraph: {
          $type: "typography",
          $value: "400 1rem/1.625rem Inter",
          $description: "Article paragraph text.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.400}",
              fontSize: "{fontSize.3}",
              lineHeight: "{lineHeight.3.relaxed}",
              letterSpacing: "{tracking.normal}",
            },
            $description: "Article paragraph text.",
          },
          name: "cn-component-markdown-editor-content-paragraph",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "content",
            subitem: "paragraph",
          },
          path: ["component", "markdown-editor", "content", "paragraph"],
        },
        emphasized: {
          $type: "typography",
          $value: "500 1rem/1.625rem Inter",
          $description: "Emphasized paragraph text.",
          filePath: "design-tokens/breakpoint/desktop.json",
          isSource: true,
          original: {
            $type: "typography",
            $value: {
              fontFamily: "{fontFamily.default}",
              fontWeight: "{fontWeight.default.normal.500}",
              fontSize: "{fontSize.3}",
              lineHeight: "{lineHeight.3.relaxed}",
              letterSpacing: "{tracking.tight}",
            },
            $description: "Emphasized paragraph text.",
          },
          name: "cn-component-markdown-editor-content-emphasized",
          attributes: {
            category: "component",
            type: "markdown-editor",
            item: "content",
            subitem: "emphasized",
          },
          path: ["component", "markdown-editor", "content", "emphasized"],
        },
      },
    },
  },
  breakpoint: {
    viewport: {
      $type: "number",
      $value: "1440",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "number",
        $value: "1440",
      },
      name: "cn-breakpoint-viewport",
      attributes: {
        category: "breakpoint",
        type: "viewport",
      },
      path: ["breakpoint", "viewport"],
    },
    viewportMin: {
      $type: "number",
      $value: "1080",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "number",
        $value: "1080",
      },
      name: "cn-breakpoint-viewport-min",
      attributes: {
        category: "breakpoint",
        type: "viewportMin",
      },
      path: ["breakpoint", "viewportMin"],
    },
    viewportMax: {
      $type: "number",
      $value: "1919",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "number",
        $value: "1919",
      },
      name: "cn-breakpoint-viewport-max",
      attributes: {
        category: "breakpoint",
        type: "viewportMax",
      },
      path: ["breakpoint", "viewportMax"],
    },
    container: {
      $type: "number",
      $value: "32px",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "number",
        $value: "{spacing.8}",
      },
      name: "cn-breakpoint-container",
      attributes: {
        category: "breakpoint",
        type: "container",
      },
      path: ["breakpoint", "container"],
    },
  },
  heading: {
    hero: {
      $type: "typography",
      $value: "500 3rem/3.75rem Inter",
      $description: "Large headlines with extra emphasis.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.9}",
          lineHeight: "{lineHeight.9.tight}",
          letterSpacing: "{tracking.tight}",
          textCase: "{textCase.none}",
        },
        $description: "Large headlines with extra emphasis.",
      },
      name: "cn-heading-hero",
      attributes: {
        category: "heading",
        type: "hero",
      },
      path: ["heading", "hero"],
    },
    section: {
      $type: "typography",
      $value: "500 1.875rem/2.3438rem Inter",
      $description: "Large headlines, hero sections.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.7}",
          lineHeight: "{lineHeight.7.tight}",
          letterSpacing: "{tracking.tight}",
          textCase: "{textCase.none}",
        },
        $description: "Large headlines, hero sections.",
      },
      name: "cn-heading-section",
      attributes: {
        category: "heading",
        type: "section",
      },
      path: ["heading", "section"],
    },
    subsection: {
      $type: "typography",
      $value: "500 1.5rem/1.875rem Inter",
      $description: "Emphasized section headers.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.6}",
          lineHeight: "{lineHeight.6.tight}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Emphasized section headers.",
      },
      name: "cn-heading-subsection",
      attributes: {
        category: "heading",
        type: "subsection",
      },
      path: ["heading", "subsection"],
    },
    dialog: {
      $type: "typography",
      $value: "500 1.25rem/1.5625rem Inter",
      $description: "Dialog headers.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.5}",
          lineHeight: "{lineHeight.5.tight}",
          letterSpacing: "{tracking.tight}",
        },
        $description: "Dialog headers.",
      },
      name: "cn-heading-dialog",
      attributes: {
        category: "heading",
        type: "dialog",
      },
      path: ["heading", "dialog"],
    },
    base: {
      $type: "typography",
      $value: "500 1rem/1.25rem Inter",
      $description: "Section headers.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.3}",
          lineHeight: "{lineHeight.3.tight}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Section headers.",
      },
      name: "cn-heading-base",
      attributes: {
        category: "heading",
        type: "base",
      },
      path: ["heading", "base"],
    },
    small: {
      $type: "typography",
      $value: "600 0.875rem/1.2031rem Inter",
      $description: "Section headers.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.600}",
          fontSize: "{fontSize.2}",
          lineHeight: "{lineHeight.2.snug}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Section headers.",
      },
      name: "cn-heading-small",
      attributes: {
        category: "heading",
        type: "small",
      },
      path: ["heading", "small"],
    },
  },
  body: {
    normal: {
      $type: "typography",
      $value: "400 0.875rem/1.2031rem Inter",
      $description: "Primary text style for UI and content.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.400}",
          fontSize: "{fontSize.2}",
          lineHeight: "{lineHeight.2.snug}",
          letterSpacing: "{tracking.tight}",
        },
        $description: "Primary text style for UI and content.",
      },
      name: "cn-body-normal",
      attributes: {
        category: "body",
        type: "normal",
      },
      path: ["body", "normal"],
    },
    strong: {
      $type: "typography",
      $value: "500 0.875rem/1.2031rem Inter",
      $description: "Primary text style for UI and content.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.2}",
          lineHeight: "{lineHeight.2.snug}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Primary text style for UI and content.",
      },
      name: "cn-body-strong",
      attributes: {
        category: "body",
        type: "strong",
      },
      path: ["body", "strong"],
    },
    code: {
      $type: "typography",
      $value: "400 0.875rem/1.3125rem 'JetBrains Mono'",
      $description: "Code blocks and larger code snippets.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.mono}",
          fontWeight: "{fontWeight.default.normal.400}",
          fontSize: "{fontSize.2}",
          lineHeight: "{lineHeight.2.normal}",
          letterSpacing: "{tracking.tight}",
        },
        $description: "Code blocks and larger code snippets.",
      },
      name: "cn-body-code",
      attributes: {
        category: "body",
        type: "code",
      },
      path: ["body", "code"],
    },
    none: {
      normal: {
        $type: "typography",
        $value: "400 0.875rem/0.875rem Inter",
        $description: "Primary text style for UI and content.",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.400}",
            fontSize: "{fontSize.2}",
            lineHeight: "{lineHeight.2.none}",
            letterSpacing: "{tracking.tight}",
          },
          $description: "Primary text style for UI and content.",
        },
        name: "cn-body-none-normal",
        attributes: {
          category: "body",
          type: "none",
          item: "normal",
        },
        path: ["body", "none", "normal"],
      },
      strong: {
        $type: "typography",
        $value: "500 0.875rem/0.875rem Inter",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.500}",
            fontSize: "{fontSize.2}",
            lineHeight: "{lineHeight.2.none}",
            letterSpacing: "{tracking.normal}",
          },
        },
        name: "cn-body-none-strong",
        attributes: {
          category: "body",
          type: "none",
          item: "strong",
        },
        path: ["body", "none", "strong"],
      },
    },
    tight: {
      normal: {
        $type: "typography",
        $value: "400 0.875rem/1.0938rem Inter",
        $description: "Primary text style for UI and content.",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.400}",
            fontSize: "{fontSize.2}",
            lineHeight: "{lineHeight.2.tight}",
            letterSpacing: "{tracking.tight}",
          },
          $description: "Primary text style for UI and content.",
        },
        name: "cn-body-tight-normal",
        attributes: {
          category: "body",
          type: "tight",
          item: "normal",
        },
        path: ["body", "tight", "normal"],
      },
      strong: {
        $type: "typography",
        $value: "500 0.875rem/1.0938rem Inter",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.500}",
            fontSize: "{fontSize.2}",
            lineHeight: "{lineHeight.2.tight}",
            letterSpacing: "{tracking.normal}",
          },
        },
        name: "cn-body-tight-strong",
        attributes: {
          category: "body",
          type: "tight",
          item: "strong",
        },
        path: ["body", "tight", "strong"],
      },
    },
  },
  caption: {
    normal: {
      $type: "typography",
      $value: "500 0.75rem/1.0313rem Inter",
      $description: "Primary caption style, small but important text.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.500}",
          fontSize: "{fontSize.1}",
          lineHeight: "{lineHeight.1.snug}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Primary caption style, small but important text.",
      },
      name: "cn-caption-normal",
      attributes: {
        category: "caption",
        type: "normal",
      },
      path: ["caption", "normal"],
    },
    soft: {
      $type: "typography",
      $value: "400 0.75rem/1.0313rem Inter",
      $description: "Helper text, meta information.",
      filePath: "design-tokens/breakpoint/desktop.json",
      isSource: true,
      original: {
        $type: "typography",
        $value: {
          fontFamily: "{fontFamily.default}",
          fontWeight: "{fontWeight.default.normal.400}",
          fontSize: "{fontSize.1}",
          lineHeight: "{lineHeight.1.snug}",
          letterSpacing: "{tracking.normal}",
        },
        $description: "Helper text, meta information.",
      },
      name: "cn-caption-soft",
      attributes: {
        category: "caption",
        type: "soft",
      },
      path: ["caption", "soft"],
    },
    none: {
      normal: {
        $type: "typography",
        $value: "500 0.75rem/0.75rem Inter",
        $description: "Primary caption style, small but important text.",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.500}",
            fontSize: "{fontSize.1}",
            lineHeight: "{lineHeight.1.none}",
            letterSpacing: "{tracking.normal}",
          },
          $description: "Primary caption style, small but important text.",
        },
        name: "cn-caption-none-normal",
        attributes: {
          category: "caption",
          type: "none",
          item: "normal",
        },
        path: ["caption", "none", "normal"],
      },
      soft: {
        $type: "typography",
        $value: "400 0.75rem/0.75rem Inter",
        $description: "Helper text, meta information.",
        filePath: "design-tokens/breakpoint/desktop.json",
        isSource: true,
        original: {
          $type: "typography",
          $value: {
            fontFamily: "{fontFamily.default}",
            fontWeight: "{fontWeight.default.normal.400}",
            fontSize: "{fontSize.1}",
            lineHeight: "{lineHeight.1.none}",
            letterSpacing: "{tracking.normal}",
          },
          $description: "Helper text, meta information.",
        },
        name: "cn-caption-none-soft",
        attributes: {
          category: "caption",
          type: "none",
          item: "soft",
        },
        path: ["caption", "none", "soft"],
      },
    },
  },
};
