/**
 * Harness Design System
 * Generated style tokens - DO NOT EDIT DIRECTLY
 * Copyright (c) Harness.
 */

export default {
  colors: {
    pure: {
      white: {
        $value: "lch(100% 0 134.54)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(100% 0 134.54)",
          $type: "color",
        },
        name: "cn-colors-pure-white",
        attributes: {
          category: "colors",
          type: "pure",
          item: "white",
        },
        path: ["colors", "pure", "white"],
      },
      black: {
        $value: "lch(2.44% 1.49 285.81)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.44% 1.49 285.81)",
          $type: "color",
        },
        name: "cn-colors-pure-black",
        attributes: {
          category: "colors",
          type: "pure",
          item: "black",
        },
        path: ["colors", "pure", "black"],
      },
    },
    chrome: {
      50: {
        $value: "lch(98.27% 0.36 135.2)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(98.27% 0.36 135.2)",
          $type: "color",
        },
        name: "cn-colors-chrome-50",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "50",
        },
        path: ["colors", "chrome", "50"],
      },
      100: {
        $value: "lch(90.71% 0.38 284.93)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(90.71% 0.38 284.93)",
          $type: "color",
        },
        name: "cn-colors-chrome-100",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "100",
        },
        path: ["colors", "chrome", "100"],
      },
      150: {
        $value: "lch(85.99% 3.77 285.34)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(85.99% 3.77 285.34)",
          $type: "color",
        },
        name: "cn-colors-chrome-150",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "150",
        },
        path: ["colors", "chrome", "150"],
      },
      200: {
        $value: "lch(81.33% 4.52 285.46)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(81.33% 4.52 285.46)",
          $type: "color",
        },
        name: "cn-colors-chrome-200",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "200",
        },
        path: ["colors", "chrome", "200"],
      },
      300: {
        $value: "lch(74.37% 4.52 285.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(74.37% 4.52 285.5)",
          $type: "color",
        },
        name: "cn-colors-chrome-300",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "300",
        },
        path: ["colors", "chrome", "300"],
      },
      400: {
        $value: "lch(67.41% 4.51 285.56)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(67.41% 4.51 285.56)",
          $type: "color",
        },
        name: "cn-colors-chrome-400",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "400",
        },
        path: ["colors", "chrome", "400"],
      },
      500: {
        $value: "lch(58.08% 6.76 286.02)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(58.08% 6.76 286.02)",
          $type: "color",
        },
        name: "cn-colors-chrome-500",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "500",
        },
        path: ["colors", "chrome", "500"],
      },
      600: {
        $value: "lch(46.46% 7.5 286.37)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(46.46% 7.5 286.37)",
          $type: "color",
        },
        name: "cn-colors-chrome-600",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "600",
        },
        path: ["colors", "chrome", "600"],
      },
      700: {
        $value: "lch(39.46% 8.98 286.89)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(39.46% 8.98 286.89)",
          $type: "color",
        },
        name: "cn-colors-chrome-700",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "700",
        },
        path: ["colors", "chrome", "700"],
      },
      800: {
        $value: "lch(26.73% 7.48 287.06)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(26.73% 7.48 287.06)",
          $type: "color",
        },
        name: "cn-colors-chrome-800",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "800",
        },
        path: ["colors", "chrome", "800"],
      },
      850: {
        $value: "lch(18.63% 6.73 287.29)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.63% 6.73 287.29)",
          $type: "color",
        },
        name: "cn-colors-chrome-850",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "850",
        },
        path: ["colors", "chrome", "850"],
      },
      900: {
        $value: "lch(8.25% 4.49 287.18)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(8.25% 4.49 287.18)",
          $type: "color",
        },
        name: "cn-colors-chrome-900",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "900",
        },
        path: ["colors", "chrome", "900"],
      },
      950: {
        $value: "lch(5.2% 3.07 285.78)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(5.2% 3.07 285.78)",
          $type: "color",
        },
        name: "cn-colors-chrome-950",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "950",
        },
        path: ["colors", "chrome", "950"],
      },
      1000: {
        $value: "lch(3.66% 1.93 285.7)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.66% 1.93 285.7)",
          $type: "color",
        },
        name: "cn-colors-chrome-1000",
        attributes: {
          category: "colors",
          type: "chrome",
          item: "1000",
        },
        path: ["colors", "chrome", "1000"],
      },
    },
    blue: {
      50: {
        $value: "lch(95.27% 4.16 280.86)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.27% 4.16 280.86)",
          $type: "color",
        },
        name: "cn-colors-blue-50",
        attributes: {
          category: "colors",
          type: "blue",
          item: "50",
        },
        path: ["colors", "blue", "50"],
      },
      100: {
        $value: "lch(89.92% 10.91 279.8)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.92% 10.91 279.8)",
          $type: "color",
        },
        name: "cn-colors-blue-100",
        attributes: {
          category: "colors",
          type: "blue",
          item: "100",
        },
        path: ["colors", "blue", "100"],
      },
      200: {
        $value: "lch(73.08% 34.81 281.21)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(73.08% 34.81 281.21)",
          $type: "color",
        },
        name: "cn-colors-blue-200",
        attributes: {
          category: "colors",
          type: "blue",
          item: "200",
        },
        path: ["colors", "blue", "200"],
      },
      300: {
        $value: "lch(63.4% 48.44 281.2)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(63.4% 48.44 281.2)",
          $type: "color",
        },
        name: "cn-colors-blue-300",
        attributes: {
          category: "colors",
          type: "blue",
          item: "300",
        },
        path: ["colors", "blue", "300"],
      },
      400: {
        $value: "lch(54.29% 60.55 281.11)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(54.29% 60.55 281.11)",
          $type: "color",
        },
        name: "cn-colors-blue-400",
        attributes: {
          category: "colors",
          type: "blue",
          item: "400",
        },
        path: ["colors", "blue", "400"],
      },
      500: {
        $value: "lch(47.04% 69.94 279.78)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(47.04% 69.94 279.78)",
          $type: "color",
        },
        name: "cn-colors-blue-500",
        attributes: {
          category: "colors",
          type: "blue",
          item: "500",
        },
        path: ["colors", "blue", "500"],
      },
      600: {
        $value: "lch(35.67% 59.7 280.58)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(35.67% 59.7 280.58)",
          $type: "color",
        },
        name: "cn-colors-blue-600",
        attributes: {
          category: "colors",
          type: "blue",
          item: "600",
        },
        path: ["colors", "blue", "600"],
      },
      700: {
        $value: "lch(27.25% 49.8 280.51)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(27.25% 49.8 280.51)",
          $type: "color",
        },
        name: "cn-colors-blue-700",
        attributes: {
          category: "colors",
          type: "blue",
          item: "700",
        },
        path: ["colors", "blue", "700"],
      },
      800: {
        $value: "lch(18.28% 39.2 280.4)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.28% 39.2 280.4)",
          $type: "color",
        },
        name: "cn-colors-blue-800",
        attributes: {
          category: "colors",
          type: "blue",
          item: "800",
        },
        path: ["colors", "blue", "800"],
      },
      900: {
        $value: "lch(9.63% 33.17 284.31)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(9.63% 33.17 284.31)",
          $type: "color",
        },
        name: "cn-colors-blue-900",
        attributes: {
          category: "colors",
          type: "blue",
          item: "900",
        },
        path: ["colors", "blue", "900"],
      },
      950: {
        $value: "lch(2.52% 22.28 283.9)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.52% 22.28 283.9)",
          $type: "color",
        },
        name: "cn-colors-blue-950",
        attributes: {
          category: "colors",
          type: "blue",
          item: "950",
        },
        path: ["colors", "blue", "950"],
      },
    },
    cyan: {
      50: {
        $value: "lch(95.4% 5 238.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.4% 5 238.5)",
          $type: "color",
        },
        name: "cn-colors-cyan-50",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "50",
        },
        path: ["colors", "cyan", "50"],
      },
      100: {
        $value: "lch(90.24% 13.5 239.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(90.24% 13.5 239.5)",
          $type: "color",
        },
        name: "cn-colors-cyan-100",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "100",
        },
        path: ["colors", "cyan", "100"],
      },
      200: {
        $value: "lch(74.15% 29 241)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(74.15% 29 241)",
          $type: "color",
        },
        name: "cn-colors-cyan-200",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "200",
        },
        path: ["colors", "cyan", "200"],
      },
      300: {
        $value: "lch(65.49% 45.28 239)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(65.49% 45.28 239)",
          $type: "color",
        },
        name: "cn-colors-cyan-300",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "300",
        },
        path: ["colors", "cyan", "300"],
      },
      400: {
        $value: "lch(56.15% 44.5 246.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(56.15% 44.5 246.5)",
          $type: "color",
        },
        name: "cn-colors-cyan-400",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "400",
        },
        path: ["colors", "cyan", "400"],
      },
      500: {
        $value: "lch(46.84% 41.5 250)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(46.84% 41.5 250)",
          $type: "color",
        },
        name: "cn-colors-cyan-500",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "500",
        },
        path: ["colors", "cyan", "500"],
      },
      600: {
        $value: "lch(37.53% 36.5 254)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(37.53% 36.5 254)",
          $type: "color",
        },
        name: "cn-colors-cyan-600",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "600",
        },
        path: ["colors", "cyan", "600"],
      },
      700: {
        $value: "lch(28.81% 30 257.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(28.81% 30 257.5)",
          $type: "color",
        },
        name: "cn-colors-cyan-700",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "700",
        },
        path: ["colors", "cyan", "700"],
      },
      800: {
        $value: "lch(19.49% 23 261.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(19.49% 23 261.5)",
          $type: "color",
        },
        name: "cn-colors-cyan-800",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "800",
        },
        path: ["colors", "cyan", "800"],
      },
      900: {
        $value: "lch(10.76% 15.5 265)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(10.76% 15.5 265)",
          $type: "color",
        },
        name: "cn-colors-cyan-900",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "900",
        },
        path: ["colors", "cyan", "900"],
      },
      950: {
        $value: "lch(3.09% 7.5 268)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.09% 7.5 268)",
          $type: "color",
        },
        name: "cn-colors-cyan-950",
        attributes: {
          category: "colors",
          type: "cyan",
          item: "950",
        },
        path: ["colors", "cyan", "950"],
      },
    },
    red: {
      50: {
        $value: "lch(95.23% 5.25 32.59)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.23% 5.25 32.59)",
          $type: "color",
        },
        name: "cn-colors-red-50",
        attributes: {
          category: "colors",
          type: "red",
          item: "50",
        },
        path: ["colors", "red", "50"],
      },
      100: {
        $value: "lch(89.81% 13.4 32.67)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.81% 13.4 32.67)",
          $type: "color",
        },
        name: "cn-colors-red-100",
        attributes: {
          category: "colors",
          type: "red",
          item: "100",
        },
        path: ["colors", "red", "100"],
      },
      200: {
        $value: "lch(72.7% 48.17 33.53)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72.7% 48.17 33.53)",
          $type: "color",
        },
        name: "cn-colors-red-200",
        attributes: {
          category: "colors",
          type: "red",
          item: "200",
        },
        path: ["colors", "red", "200"],
      },
      300: {
        $value: "lch(65.59% 65.99 34.56)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(65.59% 65.99 34.56)",
          $type: "color",
        },
        name: "cn-colors-red-300",
        attributes: {
          category: "colors",
          type: "red",
          item: "300",
        },
        path: ["colors", "red", "300"],
      },
      400: {
        $value: "lch(53.74% 88.37 37.69)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(53.74% 88.37 37.69)",
          $type: "color",
        },
        name: "cn-colors-red-400",
        attributes: {
          category: "colors",
          type: "red",
          item: "400",
        },
        path: ["colors", "red", "400"],
      },
      500: {
        $value: "lch(44.74% 76.92 37.68)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(44.74% 76.92 37.68)",
          $type: "color",
        },
        name: "cn-colors-red-500",
        attributes: {
          category: "colors",
          type: "red",
          item: "500",
        },
        path: ["colors", "red", "500"],
      },
      600: {
        $value: "lch(35.74% 65.47 37.67)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(35.74% 65.47 37.67)",
          $type: "color",
        },
        name: "cn-colors-red-600",
        attributes: {
          category: "colors",
          type: "red",
          item: "600",
        },
        path: ["colors", "red", "600"],
      },
      700: {
        $value: "lch(27.3% 54.82 37.68)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(27.3% 54.82 37.68)",
          $type: "color",
        },
        name: "cn-colors-red-700",
        attributes: {
          category: "colors",
          type: "red",
          item: "700",
        },
        path: ["colors", "red", "700"],
      },
      800: {
        $value: "lch(18.31% 42.35 35.83)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.31% 42.35 35.83)",
          $type: "color",
        },
        name: "cn-colors-red-800",
        attributes: {
          category: "colors",
          type: "red",
          item: "800",
        },
        path: ["colors", "red", "800"],
      },
      900: {
        $value: "lch(9.87% 29.51 28.59)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(9.87% 29.51 28.59)",
          $type: "color",
        },
        name: "cn-colors-red-900",
        attributes: {
          category: "colors",
          type: "red",
          item: "900",
        },
        path: ["colors", "red", "900"],
      },
      950: {
        $value: "lch(2.8% 10.22 21.65)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.8% 10.22 21.65)",
          $type: "color",
        },
        name: "cn-colors-red-950",
        attributes: {
          category: "colors",
          type: "red",
          item: "950",
        },
        path: ["colors", "red", "950"],
      },
    },
    pink: {
      50: {
        $value: "lch(95.15% 5.42 350.29)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.15% 5.42 350.29)",
          $type: "color",
        },
        name: "cn-colors-pink-50",
        attributes: {
          category: "colors",
          type: "pink",
          item: "50",
        },
        path: ["colors", "pink", "50"],
      },
      100: {
        $value: "lch(89.61% 13.47 350.26)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.61% 13.47 350.26)",
          $type: "color",
        },
        name: "cn-colors-pink-100",
        attributes: {
          category: "colors",
          type: "pink",
          item: "100",
        },
        path: ["colors", "pink", "100"],
      },
      200: {
        $value: "lch(72% 46.72 350.11)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72% 46.72 350.11)",
          $type: "color",
        },
        name: "cn-colors-pink-200",
        attributes: {
          category: "colors",
          type: "pink",
          item: "200",
        },
        path: ["colors", "pink", "200"],
      },
      300: {
        $value: "lch(61.26% 69.37 350)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(61.26% 69.37 350)",
          $type: "color",
        },
        name: "cn-colors-pink-300",
        attributes: {
          category: "colors",
          type: "pink",
          item: "300",
        },
        path: ["colors", "pink", "300"],
      },
      400: {
        $value: "lch(53.21% 65.17 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(53.21% 65.17 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-400",
        attributes: {
          category: "colors",
          type: "pink",
          item: "400",
        },
        path: ["colors", "pink", "400"],
      },
      500: {
        $value: "lch(44.27% 56.78 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(44.27% 56.78 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-500",
        attributes: {
          category: "colors",
          type: "pink",
          item: "500",
        },
        path: ["colors", "pink", "500"],
      },
      600: {
        $value: "lch(35.34% 48.39 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(35.34% 48.39 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-600",
        attributes: {
          category: "colors",
          type: "pink",
          item: "600",
        },
        path: ["colors", "pink", "600"],
      },
      700: {
        $value: "lch(26.98% 40.34 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(26.98% 40.34 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-700",
        attributes: {
          category: "colors",
          type: "pink",
          item: "700",
        },
        path: ["colors", "pink", "700"],
      },
      800: {
        $value: "lch(18.05% 31.95 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.05% 31.95 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-800",
        attributes: {
          category: "colors",
          type: "pink",
          item: "800",
        },
        path: ["colors", "pink", "800"],
      },
      900: {
        $value: "lch(9.69% 23.89 349.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(9.69% 23.89 349.99)",
          $type: "color",
        },
        name: "cn-colors-pink-900",
        attributes: {
          category: "colors",
          type: "pink",
          item: "900",
        },
        path: ["colors", "pink", "900"],
      },
      950: {
        $value: "lch(2.74% 8.62 350.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.74% 8.62 350.99)",
          $type: "color",
        },
        name: "cn-colors-pink-950",
        attributes: {
          category: "colors",
          type: "pink",
          item: "950",
        },
        path: ["colors", "pink", "950"],
      },
    },
    peach: {
      50: {
        $value: "lch(95.22% 5.2 27.21)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.22% 5.2 27.21)",
          $type: "color",
        },
        name: "cn-colors-peach-50",
        attributes: {
          category: "colors",
          type: "peach",
          item: "50",
        },
        path: ["colors", "peach", "50"],
      },
      100: {
        $value: "lch(89.79% 12.88 27.31)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.79% 12.88 27.31)",
          $type: "color",
        },
        name: "cn-colors-peach-100",
        attributes: {
          category: "colors",
          type: "peach",
          item: "100",
        },
        path: ["colors", "peach", "100"],
      },
      200: {
        $value: "lch(72.22% 46.73 23.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72.22% 46.73 23.25)",
          $type: "color",
        },
        name: "cn-colors-peach-200",
        attributes: {
          category: "colors",
          type: "peach",
          item: "200",
        },
        path: ["colors", "peach", "200"],
      },
      300: {
        $value: "lch(62.66% 70.81 29.46)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(62.66% 70.81 29.46)",
          $type: "color",
        },
        name: "cn-colors-peach-300",
        attributes: {
          category: "colors",
          type: "peach",
          item: "300",
        },
        path: ["colors", "peach", "300"],
      },
      400: {
        $value: "lch(53.64% 82.24 30.93)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(53.64% 82.24 30.93)",
          $type: "color",
        },
        name: "cn-colors-peach-400",
        attributes: {
          category: "colors",
          type: "peach",
          item: "400",
        },
        path: ["colors", "peach", "400"],
      },
      500: {
        $value: "lch(44.66% 71.48 30.92)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(44.66% 71.48 30.92)",
          $type: "color",
        },
        name: "cn-colors-peach-500",
        attributes: {
          category: "colors",
          type: "peach",
          item: "500",
        },
        path: ["colors", "peach", "500"],
      },
      600: {
        $value: "lch(35.68% 60.73 30.9)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(35.68% 60.73 30.9)",
          $type: "color",
        },
        name: "cn-colors-peach-600",
        attributes: {
          category: "colors",
          type: "peach",
          item: "600",
        },
        path: ["colors", "peach", "600"],
      },
      700: {
        $value: "lch(27.25% 50.72 30.88)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(27.25% 50.72 30.88)",
          $type: "color",
        },
        name: "cn-colors-peach-700",
        attributes: {
          category: "colors",
          type: "peach",
          item: "700",
        },
        path: ["colors", "peach", "700"],
      },
      800: {
        $value: "lch(18.26% 40.26 30.65)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.26% 40.26 30.65)",
          $type: "color",
        },
        name: "cn-colors-peach-800",
        attributes: {
          category: "colors",
          type: "peach",
          item: "800",
        },
        path: ["colors", "peach", "800"],
      },
      900: {
        $value: "lch(9.84% 28.78 25.16)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(9.84% 28.78 25.16)",
          $type: "color",
        },
        name: "cn-colors-peach-900",
        attributes: {
          category: "colors",
          type: "peach",
          item: "900",
        },
        path: ["colors", "peach", "900"],
      },
      950: {
        $value: "lch(2.79% 10.24 18.76)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.79% 10.24 18.76)",
          $type: "color",
        },
        name: "cn-colors-peach-950",
        attributes: {
          category: "colors",
          type: "peach",
          item: "950",
        },
        path: ["colors", "peach", "950"],
      },
    },
    yellow: {
      50: {
        $value: "lch(95.62% 18.31 92.87)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.62% 18.31 92.87)",
          $type: "color",
        },
        name: "cn-colors-yellow-50",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "50",
        },
        path: ["colors", "yellow", "50"],
      },
      100: {
        $value: "lch(90.23% 26.34 77.18)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(90.23% 26.34 77.18)",
          $type: "color",
        },
        name: "cn-colors-yellow-100",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "100",
        },
        path: ["colors", "yellow", "100"],
      },
      200: {
        $value: "lch(73.82% 74.92 75.35)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(73.82% 74.92 75.35)",
          $type: "color",
        },
        name: "cn-colors-yellow-200",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "200",
        },
        path: ["colors", "yellow", "200"],
      },
      300: {
        $value: "lch(64.58% 68.1 76.07)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(64.58% 68.1 76.07)",
          $type: "color",
        },
        name: "cn-colors-yellow-300",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "300",
        },
        path: ["colors", "yellow", "300"],
      },
      400: {
        $value: "lch(55.9% 60.21 76.41)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(55.9% 60.21 76.41)",
          $type: "color",
        },
        name: "cn-colors-yellow-400",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "400",
        },
        path: ["colors", "yellow", "400"],
      },
      500: {
        $value: "lch(46.64% 52.59 77.11)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(46.64% 52.59 77.11)",
          $type: "color",
        },
        name: "cn-colors-yellow-500",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "500",
        },
        path: ["colors", "yellow", "500"],
      },
      600: {
        $value: "lch(37.37% 44.92 77.47)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(37.37% 44.92 77.47)",
          $type: "color",
        },
        name: "cn-colors-yellow-600",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "600",
        },
        path: ["colors", "yellow", "600"],
      },
      700: {
        $value: "lch(28.67% 36.97 77.45)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(28.67% 36.97 77.45)",
          $type: "color",
        },
        name: "cn-colors-yellow-700",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "700",
        },
        path: ["colors", "yellow", "700"],
      },
      800: {
        $value: "lch(19.4% 27.53 77.01)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(19.4% 27.53 77.01)",
          $type: "color",
        },
        name: "cn-colors-yellow-800",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "800",
        },
        path: ["colors", "yellow", "800"],
      },
      900: {
        $value: "lch(10.69% 16.28 73.34)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(10.69% 16.28 73.34)",
          $type: "color",
        },
        name: "cn-colors-yellow-900",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "900",
        },
        path: ["colors", "yellow", "900"],
      },
      950: {
        $value: "lch(3.06% 4.5 71.6)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.06% 4.5 71.6)",
          $type: "color",
        },
        name: "cn-colors-yellow-950",
        attributes: {
          category: "colors",
          type: "yellow",
          item: "950",
        },
        path: ["colors", "yellow", "950"],
      },
    },
    orange: {
      50: {
        $value: "lch(95.42% 10.03 79.83)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.42% 10.03 79.83)",
          $type: "color",
        },
        name: "cn-colors-orange-50",
        attributes: {
          category: "colors",
          type: "orange",
          item: "50",
        },
        path: ["colors", "orange", "50"],
      },
      100: {
        $value: "lch(90.02% 17.62 61.56)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(90.02% 17.62 61.56)",
          $type: "color",
        },
        name: "cn-colors-orange-100",
        attributes: {
          category: "colors",
          type: "orange",
          item: "100",
        },
        path: ["colors", "orange", "100"],
      },
      200: {
        $value: "lch(74.82% 51.93 49.87)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(74.82% 51.93 49.87)",
          $type: "color",
        },
        name: "cn-colors-orange-200",
        attributes: {
          category: "colors",
          type: "orange",
          item: "200",
        },
        path: ["colors", "orange", "200"],
      },
      300: {
        $value: "lch(63.38% 78.04 52.26)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(63.38% 78.04 52.26)",
          $type: "color",
        },
        name: "cn-colors-orange-300",
        attributes: {
          category: "colors",
          type: "orange",
          item: "300",
        },
        path: ["colors", "orange", "300"],
      },
      400: {
        $value: "lch(54.81% 69.74 52.27)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(54.81% 69.74 52.27)",
          $type: "color",
        },
        name: "cn-colors-orange-400",
        attributes: {
          category: "colors",
          type: "orange",
          item: "400",
        },
        path: ["colors", "orange", "400"],
      },
      500: {
        $value: "lch(45.68% 60.45 52.23)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(45.68% 60.45 52.23)",
          $type: "color",
        },
        name: "cn-colors-orange-500",
        attributes: {
          category: "colors",
          type: "orange",
          item: "500",
        },
        path: ["colors", "orange", "500"],
      },
      600: {
        $value: "lch(36.54% 51.77 52.28)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(36.54% 51.77 52.28)",
          $type: "color",
        },
        name: "cn-colors-orange-600",
        attributes: {
          category: "colors",
          type: "orange",
          item: "600",
        },
        path: ["colors", "orange", "600"],
      },
      700: {
        $value: "lch(27.78% 46.26 47.39)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(27.78% 46.26 47.39)",
          $type: "color",
        },
        name: "cn-colors-orange-700",
        attributes: {
          category: "colors",
          type: "orange",
          item: "700",
        },
        path: ["colors", "orange", "700"],
      },
      800: {
        $value: "lch(18.69% 35.31 45.59)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(18.69% 35.31 45.59)",
          $type: "color",
        },
        name: "cn-colors-orange-800",
        attributes: {
          category: "colors",
          type: "orange",
          item: "800",
        },
        path: ["colors", "orange", "800"],
      },
      900: {
        $value: "lch(10.26% 21.63 42.58)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(10.26% 21.63 42.58)",
          $type: "color",
        },
        name: "cn-colors-orange-900",
        attributes: {
          category: "colors",
          type: "orange",
          item: "900",
        },
        path: ["colors", "orange", "900"],
      },
      950: {
        $value: "lch(2.93% 6.64 36.42)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.93% 6.64 36.42)",
          $type: "color",
        },
        name: "cn-colors-orange-950",
        attributes: {
          category: "colors",
          type: "orange",
          item: "950",
        },
        path: ["colors", "orange", "950"],
      },
    },
    brown: {
      50: {
        $value: "lch(95.55% 12.75 93.47)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.55% 12.75 93.47)",
          $type: "color",
        },
        name: "cn-colors-brown-50",
        attributes: {
          category: "colors",
          type: "brown",
          item: "50",
        },
        path: ["colors", "brown", "50"],
      },
      100: {
        $value: "lch(90.24% 19.27 79.52)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(90.24% 19.27 79.52)",
          $type: "color",
        },
        name: "cn-colors-brown-100",
        attributes: {
          category: "colors",
          type: "brown",
          item: "100",
        },
        path: ["colors", "brown", "100"],
      },
      200: {
        $value: "lch(73.38% 45.67 56.65)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(73.38% 45.67 56.65)",
          $type: "color",
        },
        name: "cn-colors-brown-200",
        attributes: {
          category: "colors",
          type: "brown",
          item: "200",
        },
        path: ["colors", "brown", "200"],
      },
      300: {
        $value: "lch(64.06% 48.96 57.29)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(64.06% 48.96 57.29)",
          $type: "color",
        },
        name: "cn-colors-brown-300",
        attributes: {
          category: "colors",
          type: "brown",
          item: "300",
        },
        path: ["colors", "brown", "300"],
      },
      400: {
        $value: "lch(57.17% 44.39 57.69)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(57.17% 44.39 57.69)",
          $type: "color",
        },
        name: "cn-colors-brown-400",
        attributes: {
          category: "colors",
          type: "brown",
          item: "400",
        },
        path: ["colors", "brown", "400"],
      },
      500: {
        $value: "lch(46.22% 37.68 57.68)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(46.22% 37.68 57.68)",
          $type: "color",
        },
        name: "cn-colors-brown-500",
        attributes: {
          category: "colors",
          type: "brown",
          item: "500",
        },
        path: ["colors", "brown", "500"],
      },
      600: {
        $value: "lch(37.01% 31.77 57.67)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(37.01% 31.77 57.67)",
          $type: "color",
        },
        name: "cn-colors-brown-600",
        attributes: {
          category: "colors",
          type: "brown",
          item: "600",
        },
        path: ["colors", "brown", "600"],
      },
      700: {
        $value: "lch(28.37% 26.84 58.1)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(28.37% 26.84 58.1)",
          $type: "color",
        },
        name: "cn-colors-brown-700",
        attributes: {
          category: "colors",
          type: "brown",
          item: "700",
        },
        path: ["colors", "brown", "700"],
      },
      800: {
        $value: "lch(19.16% 20.96 58.49)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(19.16% 20.96 58.49)",
          $type: "color",
        },
        name: "cn-colors-brown-800",
        attributes: {
          category: "colors",
          type: "brown",
          item: "800",
        },
        path: ["colors", "brown", "800"],
      },
      900: {
        $value: "lch(10.55% 13.64 57.69)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(10.55% 13.64 57.69)",
          $type: "color",
        },
        name: "cn-colors-brown-900",
        attributes: {
          category: "colors",
          type: "brown",
          item: "900",
        },
        path: ["colors", "brown", "900"],
      },
      950: {
        $value: "lch(3% 4.01 51.14)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3% 4.01 51.14)",
          $type: "color",
        },
        name: "cn-colors-brown-950",
        attributes: {
          category: "colors",
          type: "brown",
          item: "950",
        },
        path: ["colors", "brown", "950"],
      },
    },
    green: {
      50: {
        $value: "lch(95.82% 11.79 156.15)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.82% 11.79 156.15)",
          $type: "color",
        },
        name: "cn-colors-green-50",
        attributes: {
          category: "colors",
          type: "green",
          item: "50",
        },
        path: ["colors", "green", "50"],
      },
      100: {
        $value: "lch(91.19% 27.27 156.17)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(91.19% 27.27 156.17)",
          $type: "color",
        },
        name: "cn-colors-green-100",
        attributes: {
          category: "colors",
          type: "green",
          item: "100",
        },
        path: ["colors", "green", "100"],
      },
      200: {
        $value: "lch(73.78% 60.44 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(73.78% 60.44 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-200",
        attributes: {
          category: "colors",
          type: "green",
          item: "200",
        },
        path: ["colors", "green", "200"],
      },
      300: {
        $value: "lch(66.65% 55.77 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(66.65% 55.77 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-300",
        attributes: {
          category: "colors",
          type: "green",
          item: "300",
        },
        path: ["colors", "green", "300"],
      },
      400: {
        $value: "lch(57.73% 49.65 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(57.73% 49.65 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-400",
        attributes: {
          category: "colors",
          type: "green",
          item: "400",
        },
        path: ["colors", "green", "400"],
      },
      500: {
        $value: "lch(48.21% 43.17 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(48.21% 43.17 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-500",
        attributes: {
          category: "colors",
          type: "green",
          item: "500",
        },
        path: ["colors", "green", "500"],
      },
      600: {
        $value: "lch(38.71% 37.07 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(38.71% 37.07 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-600",
        attributes: {
          category: "colors",
          type: "green",
          item: "600",
        },
        path: ["colors", "green", "600"],
      },
      700: {
        $value: "lch(29.79% 30.94 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(29.79% 30.94 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-700",
        attributes: {
          category: "colors",
          type: "green",
          item: "700",
        },
        path: ["colors", "green", "700"],
      },
      800: {
        $value: "lch(20.26% 24.09 156.25)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(20.26% 24.09 156.25)",
          $type: "color",
        },
        name: "cn-colors-green-800",
        attributes: {
          category: "colors",
          type: "green",
          item: "800",
        },
        path: ["colors", "green", "800"],
      },
      900: {
        $value: "lch(11.35% 18.27 156.36)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(11.35% 18.27 156.36)",
          $type: "color",
        },
        name: "cn-colors-green-900",
        attributes: {
          category: "colors",
          type: "green",
          item: "900",
        },
        path: ["colors", "green", "900"],
      },
      950: {
        $value: "lch(3.27% 5.33 156.53)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.27% 5.33 156.53)",
          $type: "color",
        },
        name: "cn-colors-green-950",
        attributes: {
          category: "colors",
          type: "green",
          item: "950",
        },
        path: ["colors", "green", "950"],
      },
    },
    mint: {
      50: {
        $value: "lch(95.82% 11.97 171.06)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.82% 11.97 171.06)",
          $type: "color",
        },
        name: "cn-colors-mint-50",
        attributes: {
          category: "colors",
          type: "mint",
          item: "50",
        },
        path: ["colors", "mint", "50"],
      },
      100: {
        $value: "lch(91.09% 25.48 176.08)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(91.09% 25.48 176.08)",
          $type: "color",
        },
        name: "cn-colors-mint-100",
        attributes: {
          category: "colors",
          type: "mint",
          item: "100",
        },
        path: ["colors", "mint", "100"],
      },
      200: {
        $value: "lch(73.4% 50.15 176.67)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(73.4% 50.15 176.67)",
          $type: "color",
        },
        name: "cn-colors-mint-200",
        attributes: {
          category: "colors",
          type: "mint",
          item: "200",
        },
        path: ["colors", "mint", "200"],
      },
      300: {
        $value: "lch(66.3% 46.27 176.67)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(66.3% 46.27 176.67)",
          $type: "color",
        },
        name: "cn-colors-mint-300",
        attributes: {
          category: "colors",
          type: "mint",
          item: "300",
        },
        path: ["colors", "mint", "300"],
      },
      400: {
        $value: "lch(57.46% 42.15 174.53)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(57.46% 42.15 174.53)",
          $type: "color",
        },
        name: "cn-colors-mint-400",
        attributes: {
          category: "colors",
          type: "mint",
          item: "400",
        },
        path: ["colors", "mint", "400"],
      },
      500: {
        $value: "lch(48.03% 37.67 171.84)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(48.03% 37.67 171.84)",
          $type: "color",
        },
        name: "cn-colors-mint-500",
        attributes: {
          category: "colors",
          type: "mint",
          item: "500",
        },
        path: ["colors", "mint", "500"],
      },
      600: {
        $value: "lch(38.59% 33.16 169.14)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(38.59% 33.16 169.14)",
          $type: "color",
        },
        name: "cn-colors-mint-600",
        attributes: {
          category: "colors",
          type: "mint",
          item: "600",
        },
        path: ["colors", "mint", "600"],
      },
      700: {
        $value: "lch(29.72% 28.6 166.42)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(29.72% 28.6 166.42)",
          $type: "color",
        },
        name: "cn-colors-mint-700",
        attributes: {
          category: "colors",
          type: "mint",
          item: "700",
        },
        path: ["colors", "mint", "700"],
      },
      800: {
        $value: "lch(20.24% 23.29 164.22)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(20.24% 23.29 164.22)",
          $type: "color",
        },
        name: "cn-colors-mint-800",
        attributes: {
          category: "colors",
          type: "mint",
          item: "800",
        },
        path: ["colors", "mint", "800"],
      },
      900: {
        $value: "lch(11.35% 18.26 160.23)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(11.35% 18.26 160.23)",
          $type: "color",
        },
        name: "cn-colors-mint-900",
        attributes: {
          category: "colors",
          type: "mint",
          item: "900",
        },
        path: ["colors", "mint", "900"],
      },
      950: {
        $value: "lch(3.26% 5.16 160.96)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.26% 5.16 160.96)",
          $type: "color",
        },
        name: "cn-colors-mint-950",
        attributes: {
          category: "colors",
          type: "mint",
          item: "950",
        },
        path: ["colors", "mint", "950"],
      },
    },
    lime: {
      50: {
        $value: "lch(95.86% 15.3 127.41)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.86% 15.3 127.41)",
          $type: "color",
        },
        name: "cn-colors-lime-50",
        attributes: {
          category: "colors",
          type: "lime",
          item: "50",
        },
        path: ["colors", "lime", "50"],
      },
      100: {
        $value: "lch(91.05% 29.33 126.46)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(91.05% 29.33 126.46)",
          $type: "color",
        },
        name: "cn-colors-lime-100",
        attributes: {
          category: "colors",
          type: "lime",
          item: "100",
        },
        path: ["colors", "lime", "100"],
      },
      200: {
        $value: "lch(74.24% 53.56 123.85)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(74.24% 53.56 123.85)",
          $type: "color",
        },
        name: "cn-colors-lime-200",
        attributes: {
          category: "colors",
          type: "lime",
          item: "200",
        },
        path: ["colors", "lime", "200"],
      },
      300: {
        $value: "lch(65.98% 48.66 123.85)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(65.98% 48.66 123.85)",
          $type: "color",
        },
        name: "cn-colors-lime-300",
        attributes: {
          category: "colors",
          type: "lime",
          item: "300",
        },
        path: ["colors", "lime", "300"],
      },
      400: {
        $value: "lch(57.13% 43.37 123.85)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(57.13% 43.37 123.85)",
          $type: "color",
        },
        name: "cn-colors-lime-400",
        attributes: {
          category: "colors",
          type: "lime",
          item: "400",
        },
        path: ["colors", "lime", "400"],
      },
      500: {
        $value: "lch(47.69% 37.71 123.86)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(47.69% 37.71 123.86)",
          $type: "color",
        },
        name: "cn-colors-lime-500",
        attributes: {
          category: "colors",
          type: "lime",
          item: "500",
        },
        path: ["colors", "lime", "500"],
      },
      600: {
        $value: "lch(38.26% 32.05 123.88)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(38.26% 32.05 123.88)",
          $type: "color",
        },
        name: "cn-colors-lime-600",
        attributes: {
          category: "colors",
          type: "lime",
          item: "600",
        },
        path: ["colors", "lime", "600"],
      },
      700: {
        $value: "lch(29.42% 27.17 123.81)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(29.42% 27.17 123.81)",
          $type: "color",
        },
        name: "cn-colors-lime-700",
        attributes: {
          category: "colors",
          type: "lime",
          item: "700",
        },
        path: ["colors", "lime", "700"],
      },
      800: {
        $value: "lch(19.97% 21.1 123.91)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(19.97% 21.1 123.91)",
          $type: "color",
        },
        name: "cn-colors-lime-800",
        attributes: {
          category: "colors",
          type: "lime",
          item: "800",
        },
        path: ["colors", "lime", "800"],
      },
      900: {
        $value: "lch(11.12% 14.71 126.9)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(11.12% 14.71 126.9)",
          $type: "color",
        },
        name: "cn-colors-lime-900",
        attributes: {
          category: "colors",
          type: "lime",
          item: "900",
        },
        path: ["colors", "lime", "900"],
      },
      950: {
        $value: "lch(3.2% 4.34 131.4)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(3.2% 4.34 131.4)",
          $type: "color",
        },
        name: "cn-colors-lime-950",
        attributes: {
          category: "colors",
          type: "lime",
          item: "950",
        },
        path: ["colors", "lime", "950"],
      },
    },
    purple: {
      50: {
        $value: "lch(95.14% 7 301.11)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.14% 7 301.11)",
          $type: "color",
        },
        name: "cn-colors-purple-50",
        attributes: {
          category: "colors",
          type: "purple",
          item: "50",
        },
        path: ["colors", "purple", "50"],
      },
      100: {
        $value: "lch(89.58% 17.29 301.92)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.58% 17.29 301.92)",
          $type: "color",
        },
        name: "cn-colors-purple-100",
        attributes: {
          category: "colors",
          type: "purple",
          item: "100",
        },
        path: ["colors", "purple", "100"],
      },
      200: {
        $value: "lch(72.4% 55.68 305.19)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72.4% 55.68 305.19)",
          $type: "color",
        },
        name: "cn-colors-purple-200",
        attributes: {
          category: "colors",
          type: "purple",
          item: "200",
        },
        path: ["colors", "purple", "200"],
      },
      300: {
        $value: "lch(61.28% 80.51 307.53)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(61.28% 80.51 307.53)",
          $type: "color",
        },
        name: "cn-colors-purple-300",
        attributes: {
          category: "colors",
          type: "purple",
          item: "300",
        },
        path: ["colors", "purple", "300"],
      },
      400: {
        $value: "lch(50.99% 105.85 309.98)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(50.99% 105.85 309.98)",
          $type: "color",
        },
        name: "cn-colors-purple-400",
        attributes: {
          category: "colors",
          type: "purple",
          item: "400",
        },
        path: ["colors", "purple", "400"],
      },
      500: {
        $value: "lch(40.58% 118.62 311.84)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(40.58% 118.62 311.84)",
          $type: "color",
        },
        name: "cn-colors-purple-500",
        attributes: {
          category: "colors",
          type: "purple",
          item: "500",
        },
        path: ["colors", "purple", "500"],
      },
      600: {
        $value: "lch(32.21% 100.98 311.83)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(32.21% 100.98 311.83)",
          $type: "color",
        },
        name: "cn-colors-purple-600",
        attributes: {
          category: "colors",
          type: "purple",
          item: "600",
        },
        path: ["colors", "purple", "600"],
      },
      700: {
        $value: "lch(24.34% 84.56 311.84)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(24.34% 84.56 311.84)",
          $type: "color",
        },
        name: "cn-colors-purple-700",
        attributes: {
          category: "colors",
          type: "purple",
          item: "700",
        },
        path: ["colors", "purple", "700"],
      },
      800: {
        $value: "lch(15.97% 66.91 311.83)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(15.97% 66.91 311.83)",
          $type: "color",
        },
        name: "cn-colors-purple-800",
        attributes: {
          category: "colors",
          type: "purple",
          item: "800",
        },
        path: ["colors", "purple", "800"],
      },
      900: {
        $value: "lch(8.1% 50.49 311.83)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(8.1% 50.49 311.83)",
          $type: "color",
        },
        name: "cn-colors-purple-900",
        attributes: {
          category: "colors",
          type: "purple",
          item: "900",
        },
        path: ["colors", "purple", "900"],
      },
      950: {
        $value: "lch(2.32% 21.96 302.37)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.32% 21.96 302.37)",
          $type: "color",
        },
        name: "cn-colors-purple-950",
        attributes: {
          category: "colors",
          type: "purple",
          item: "950",
        },
        path: ["colors", "purple", "950"],
      },
    },
    violet: {
      50: {
        $value: "lch(95.18% 6.31 296.62)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.18% 6.31 296.62)",
          $type: "color",
        },
        name: "cn-colors-violet-50",
        attributes: {
          category: "colors",
          type: "violet",
          item: "50",
        },
        path: ["colors", "violet", "50"],
      },
      100: {
        $value: "lch(89.64% 16.29 297.99)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.64% 16.29 297.99)",
          $type: "color",
        },
        name: "cn-colors-violet-100",
        attributes: {
          category: "colors",
          type: "violet",
          item: "100",
        },
        path: ["colors", "violet", "100"],
      },
      200: {
        $value: "lch(72.11% 52.02 298.43)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72.11% 52.02 298.43)",
          $type: "color",
        },
        name: "cn-colors-violet-200",
        attributes: {
          category: "colors",
          type: "violet",
          item: "200",
        },
        path: ["colors", "violet", "200"],
      },
      300: {
        $value: "lch(65.15% 65.45 298.5)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(65.15% 65.45 298.5)",
          $type: "color",
        },
        name: "cn-colors-violet-300",
        attributes: {
          category: "colors",
          type: "violet",
          item: "300",
        },
        path: ["colors", "violet", "300"],
      },
      400: {
        $value: "lch(51.98% 93.37 301.42)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(51.98% 93.37 301.42)",
          $type: "color",
        },
        name: "cn-colors-violet-400",
        attributes: {
          category: "colors",
          type: "violet",
          item: "400",
        },
        path: ["colors", "violet", "400"],
      },
      500: {
        $value: "lch(40.56% 121.68 305.61)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(40.56% 121.68 305.61)",
          $type: "color",
        },
        name: "cn-colors-violet-500",
        attributes: {
          category: "colors",
          type: "violet",
          item: "500",
        },
        path: ["colors", "violet", "500"],
      },
      600: {
        $value: "lch(31.46% 113.1 306.9)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(31.46% 113.1 306.9)",
          $type: "color",
        },
        name: "cn-colors-violet-600",
        attributes: {
          category: "colors",
          type: "violet",
          item: "600",
        },
        path: ["colors", "violet", "600"],
      },
      700: {
        $value: "lch(23.77% 93.78 307.37)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(23.77% 93.78 307.37)",
          $type: "color",
        },
        name: "cn-colors-violet-700",
        attributes: {
          category: "colors",
          type: "violet",
          item: "700",
        },
        path: ["colors", "violet", "700"],
      },
      800: {
        $value: "lch(15.62% 72.5 308.3)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(15.62% 72.5 308.3)",
          $type: "color",
        },
        name: "cn-colors-violet-800",
        attributes: {
          category: "colors",
          type: "violet",
          item: "800",
        },
        path: ["colors", "violet", "800"],
      },
      900: {
        $value: "lch(8.15% 49.81 312.23)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(8.15% 49.81 312.23)",
          $type: "color",
        },
        name: "cn-colors-violet-900",
        attributes: {
          category: "colors",
          type: "violet",
          item: "900",
        },
        path: ["colors", "violet", "900"],
      },
      950: {
        $value: "lch(2.33% 21.62 302.28)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.33% 21.62 302.28)",
          $type: "color",
        },
        name: "cn-colors-violet-950",
        attributes: {
          category: "colors",
          type: "violet",
          item: "950",
        },
        path: ["colors", "violet", "950"],
      },
    },
    indigo: {
      50: {
        $value: "lch(95.23% 6.03 283.32)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(95.23% 6.03 283.32)",
          $type: "color",
        },
        name: "cn-colors-indigo-50",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "50",
        },
        path: ["colors", "indigo", "50"],
      },
      100: {
        $value: "lch(89.8% 14.62 283.7)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(89.8% 14.62 283.7)",
          $type: "color",
        },
        name: "cn-colors-indigo-100",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "100",
        },
        path: ["colors", "indigo", "100"],
      },
      200: {
        $value: "lch(72.68% 45.97 284.36)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(72.68% 45.97 284.36)",
          $type: "color",
        },
        name: "cn-colors-indigo-200",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "200",
        },
        path: ["colors", "indigo", "200"],
      },
      300: {
        $value: "lch(65.79% 58.29 283.92)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(65.79% 58.29 283.92)",
          $type: "color",
        },
        name: "cn-colors-indigo-300",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "300",
        },
        path: ["colors", "indigo", "300"],
      },
      400: {
        $value: "lch(53.15% 81.87 288.43)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(53.15% 81.87 288.43)",
          $type: "color",
        },
        name: "cn-colors-indigo-400",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "400",
        },
        path: ["colors", "indigo", "400"],
      },
      500: {
        $value: "lch(42.04% 107.17 295.8)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(42.04% 107.17 295.8)",
          $type: "color",
        },
        name: "cn-colors-indigo-500",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "500",
        },
        path: ["colors", "indigo", "500"],
      },
      600: {
        $value: "lch(30.63% 128.3 302.36)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(30.63% 128.3 302.36)",
          $type: "color",
        },
        name: "cn-colors-indigo-600",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "600",
        },
        path: ["colors", "indigo", "600"],
      },
      700: {
        $value: "lch(23.02% 107.52 302.38)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(23.02% 107.52 302.38)",
          $type: "color",
        },
        name: "cn-colors-indigo-700",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "700",
        },
        path: ["colors", "indigo", "700"],
      },
      800: {
        $value: "lch(14.93% 84.93 302.33)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(14.93% 84.93 302.33)",
          $type: "color",
        },
        name: "cn-colors-indigo-800",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "800",
        },
        path: ["colors", "indigo", "800"],
      },
      900: {
        $value: "lch(7.38% 63.51 302.14)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(7.38% 63.51 302.14)",
          $type: "color",
        },
        name: "cn-colors-indigo-900",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "900",
        },
        path: ["colors", "indigo", "900"],
      },
      950: {
        $value: "lch(2.17% 29.85 290.49)",
        filePath: "design-tokens/core/colors_lch.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "lch(2.17% 29.85 290.49)",
          $type: "color",
        },
        name: "cn-colors-indigo-950",
        attributes: {
          category: "colors",
          type: "indigo",
          item: "950",
        },
        path: ["colors", "indigo", "950"],
      },
    },
  },
};
