// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'align-right-box-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m8.005 20.005.011-.01m-4.011.01.011-.01m-.011-3.99.011-.01m-.011-3.99.011-.01m-.011-3.99.011-.01m-.011-3.99.011-.01m3.989.01.011-.01"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12.005 20.005h8v-16h-8v16Z"/></svg>`
)

export function AlignRightBoxSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

AlignRightBoxSolid.prototype.name = name
