// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'align-vertical-spacing-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M22 3H2m20 18H2"/><path fill="currentColor" stroke="currentColor" stroke-width="1.5" d="M8 15V9a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2Z"/></svg>`
)

export function AlignVerticalSpacingSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

AlignVerticalSpacingSolid.prototype.name = name
