// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'app-store-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12Zm8.847-7.133a.75.75 0 0 1 1.036.23L12 6.46l.867-1.363a.75.75 0 1 1 1.266.806l-1.244 1.954 3.432 5.393H17.5a.75.75 0 0 1 0 1.5h-.225l.858 1.347a.75.75 0 1 1-1.266.806L12 9.254 9.457 13.25H13.5a.75.75 0 0 1 0 1.5H8.503l-1.37 2.153a.75.75 0 0 1-1.266-.806l.858-1.347H6.5a.75.75 0 0 1 0-1.5h1.18l3.431-5.393-1.244-1.954a.75.75 0 0 1 .23-1.036Z" clip-rule="evenodd"/></svg>`
)

export function AppStoreSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

AppStoreSolid.prototype.name = name
