// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arc-3d-center-point/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-dasharray="3 3" stroke-linecap="round" stroke-linejoin="round" d="M22 16c0-5.523-4.477-10-10-10-4.1 0-7.625 2.468-9.168 6"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 16h10"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/></svg>`
)

export function Arc3DCenterPoint(props: IconProps) {
  return <Icon name={name} {...props} />
}

Arc3DCenterPoint.prototype.name = name
