// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arrow-up-right-square-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M3.6 2.25A1.35 1.35 0 0 0 2.25 3.6v16.8c0 .746.604 1.35 1.35 1.35h16.8a1.35 1.35 0 0 0 1.35-1.35V3.6a1.35 1.35 0 0 0-1.35-1.35H3.6Zm6.279 6.171h4.95a.747.747 0 0 1 .75.75v4.95a.75.75 0 0 1-1.5 0v-3.139l-4.377 4.377a.75.75 0 1 1-1.06-1.061l4.376-4.377h-3.14a.75.75 0 0 1 0-1.5Z" clip-rule="evenodd"/></svg>`
)

export function ArrowUpRightSquareSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

ArrowUpRightSquareSolid.prototype.name = name
