// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arrow-left-circle-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12 1.25C6.063 1.25 1.25 6.063 1.25 12S6.063 22.75 12 22.75 22.75 17.937 22.75 12 17.937 1.25 12 1.25Zm-1.03 14.78-3.5-3.5a.75.75 0 0 1 0-1.06l3.5-3.5a.75.75 0 1 1 1.06 1.06l-2.22 2.22H16a.75.75 0 0 1 0 1.5H9.81l2.22 2.22a.75.75 0 1 1-1.06 1.06Z" clip-rule="evenodd"/></svg>`
)

export function ArrowLeftCircleSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

ArrowLeftCircleSolid.prototype.name = name
