// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arrow-left/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 12H3m0 0 8.5-8.5M3 12l8.5 8.5"/></svg>`
)

export function ArrowLeft(props: IconProps) {
  return <Icon name={name} {...props} />
}

ArrowLeft.prototype.name = name
