// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arrow-separate-vertical/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m17 8-5-5-5 5m10 8-5 5-5-5"/></svg>`
)

export function ArrowSeparateVertical(props: IconProps) {
  return <Icon name={name} {...props} />
}

ArrowSeparateVertical.prototype.name = name
