// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'arrow-email-forward/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 10H8c-8 0-8 11 0 11m14-11-7-7m7 7-7 7"/></svg>`
)

export function ArrowEmailForward(props: IconProps) {
  return <Icon name={name} {...props} />
}

ArrowEmailForward.prototype.name = name
