// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'asterisk/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22V2m8.572 15.55L3.428 7.249m0 10.301L20.572 7.249"/></svg>`
)

export function Asterisk(props: IconProps) {
  return <Icon name={name} {...props} />
}

Asterisk.prototype.name = name
