// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'bright-crown/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 12h1M12 2V1m0 22v-1m8-2-1-1m1-15-1 1M4 20l1-1M4 4l1 1m-4 7h1m14.8 3.5 1.2-7-4.2 2.1L12 8.5l-1.8 2.1L6 8.5l1.2 7h9.6Z"/></svg>`
)

export function BrightCrown(props: IconProps) {
  return <Icon name={name} {...props} />
}

BrightCrown.prototype.name = name
