// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'bubble-xmark-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="m19.773 8.955-.53-.53-.53.53a2.25 2.25 0 0 1-3.183-3.182l.53-.53-.53-.53a2.25 2.25 0 0 1-.21-2.94A10.743 10.743 0 0 0 12 1.25C6.063 1.25 1.25 6.063 1.25 12c0 1.856.471 3.605 1.3 5.13l-.787 4.233a.75.75 0 0 0 .874.874l4.233-.788A10.702 10.702 0 0 0 12 22.75c5.937 0 10.75-4.813 10.75-10.75 0-.914-.114-1.802-.329-2.65a2.251 2.251 0 0 1-2.648-.395Z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M16.59 2.59a.75.75 0 0 1 1.061 0l1.591 1.592 1.591-1.591a.75.75 0 1 1 1.061 1.06l-1.591 1.591 1.591 1.591a.75.75 0 0 1-1.06 1.061l-1.592-1.59-1.59 1.59a.75.75 0 1 1-1.061-1.06l1.59-1.592-1.59-1.59a.75.75 0 0 1 0-1.061Z" clip-rule="evenodd"/></svg>`
)

export function BubbleXmarkSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

BubbleXmarkSolid.prototype.name = name
