// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'clock-rotate-right/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21.888 10.5C21.164 5.689 17.013 2 12 2 6.477 2 2 6.477 2 12s4.477 10 10 10c4.1 0 7.625-2.468 9.168-6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 16h4.4a.6.6 0 0 1 .6.6V21"/></svg>`
)

export function ClockRotateRight(props: IconProps) {
  return <Icon name={name} {...props} />
}

ClockRotateRight.prototype.name = name
