// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'closed-captions-tag-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M.25 9A6.75 6.75 0 0 1 7 2.25h10A6.75 6.75 0 0 1 23.75 9v6A6.75 6.75 0 0 1 17 21.75H7A6.75 6.75 0 0 1 .25 15V9Zm4.5 2.828a3.578 3.578 0 0 1 6.109-2.53l.171.172a.75.75 0 0 1-1.06 1.06l-.172-.171a2.078 2.078 0 0 0-3.548 1.47v.343a2.078 2.078 0 0 0 3.548 1.47l.172-.172a.75.75 0 1 1 1.06 1.06l-.171.172a3.578 3.578 0 0 1-6.109-2.53v-.344ZM16.328 8.25a3.578 3.578 0 0 0-3.578 3.578v.344a3.578 3.578 0 0 0 6.109 2.53l.171-.172a.75.75 0 1 0-1.06-1.06l-.172.171a2.079 2.079 0 0 1-3.548-1.47v-.343a2.078 2.078 0 0 1 3.548-1.47l.172.172a.75.75 0 0 0 1.06-1.06l-.171-.172a3.578 3.578 0 0 0-2.53-1.048Z" clip-rule="evenodd"/></svg>`
)

export function ClosedCaptionsTagSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

ClosedCaptionsTagSolid.prototype.name = name
