// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'cloud-sunny/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 13c-1.667 0-5 1-5 5s3.333 5 5 5h12c1.667 0 5-1 5-5s-3.333-5-5-5m-6-1a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm7-3h1m-8-7V1m6.5 2.5-1 1m-12-1 1 1M4 9h1"/></svg>`
)

export function CloudSunny(props: IconProps) {
  return <Icon name={name} {...props} />
}

CloudSunny.prototype.name = name
