// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'cloud-square-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M3.6 2.25A1.35 1.35 0 0 0 2.25 3.6v16.8c0 .746.604 1.35 1.35 1.35h16.8a1.35 1.35 0 0 0 1.35-1.35V3.6a1.35 1.35 0 0 0-1.35-1.35H3.6Zm8.4 5c-1.792 0-2.897.557-3.491 1.464-.35.536-.47 1.128-.511 1.609-.445.085-.94.255-1.388.551-.76.502-1.36 1.353-1.36 2.626s.6 2.124 1.36 2.626c.72.475 1.555.624 2.117.624h6.546c.562 0 1.398-.149 2.117-.624.76-.502 1.36-1.353 1.36-2.626s-.6-2.124-1.36-2.626a3.856 3.856 0 0 0-1.388-.551c-.04-.481-.16-1.073-.51-1.609-.595-.907-1.7-1.464-3.492-1.464Z" clip-rule="evenodd"/></svg>`
)

export function CloudSquareSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

CloudSquareSolid.prototype.name = name
