// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'color-wheel/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8Zm0-14v6m0 8v6M2 12h6m8 0h6M4.929 4.929 9.172 9.17m5.656 5.659 4.243 4.242m-14.142 0 4.243-4.242m5.656-5.658 4.243-4.242"/></svg>`
)

export function ColorWheel(props: IconProps) {
  return <Icon name={name} {...props} />
}

ColorWheel.prototype.name = name
