// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'constrained-surface/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 23a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm18 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4ZM3 5a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm18 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm-8 7c0-1.246-1.159-2.5-2.572-2.5h-.857C8.152 9.5 7 10.62 7 12c0 1.19.855 2.185 2 2.438.188.041.38.062.572.062"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 12c0 1.246 1.159 2.5 2.572 2.5h.857C15.848 14.5 17 13.38 17 12c0-1.19-.855-2.186-2-2.438a2.651 2.651 0 0 0-.572-.062M21 19V5M3 19V5m2-2h14M5 21h14"/></svg>`
)

export function ConstrainedSurface(props: IconProps) {
  return <Icon name={name} {...props} />
}

ConstrainedSurface.prototype.name = name
