// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'crib/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 5v16"/><path stroke="currentColor" stroke-linejoin="round" d="M3 16h18M3 7h18m-3 9V7m-4 9V7m-4 9V7m-4 9V7M3 19h18"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 5v16m0-16a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM3 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/></svg>`
)

export function Crib(props: IconProps) {
  return <Icon name={name} {...props} />
}

Crib.prototype.name = name
