// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'crop-rotate-tr/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 10V7a4 4 0 0 0-4-4h-4"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22.5 7.5 20 10l-2.5-2.5M14 17v-6a1 1 0 0 0-1-1H7m-5 0h2m10 12v-2M4 8v11a1 1 0 0 0 1 1h11"/></svg>`
)

export function CropRotateTr(props: IconProps) {
  return <Icon name={name} {...props} />
}

CropRotateTr.prototype.name = name
