// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'crop/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 18H6V3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 6h15v15"/></svg>`
)

export function Crop(props: IconProps) {
  return <Icon name={name} {...props} />
}

Crop.prototype.name = name
