// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'crown/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19.2 17 21 7l-6.3 3L12 7l-2.7 3L3 7l1.8 10h14.4Z"/></svg>`
)

export function Crown(props: IconProps) {
  return <Icon name={name} {...props} />
}

Crown.prototype.name = name
