// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'cut-alt/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.236 8a3 3 0 1 0-4.472-4 3 3 0 0 0 4.472 4Zm0 0L16 16m1-4h1m4 0h1M6.236 16a3 3 0 1 1-4.472 4 3 3 0 0 1 4.472-4Zm0 0L16 8"/></svg>`
)

export function CutAlt(props: IconProps) {
  return <Icon name={name} {...props} />
}

CutAlt.prototype.name = name
