// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'cylinder/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M12 2c8 0 8 3 8 3s0 3-8 3-8-3-8-3 0-3 8-3Zm0 14c8 0 8 3 8 3s0 3-8 3-8-3-8-3 0-3 8-3Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 5v14M4 5v14"/></svg>`
)

export function Cylinder(props: IconProps) {
  return <Icon name={name} {...props} />
}

Cylinder.prototype.name = name
