// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'dashboard/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M15 15.8c0-1.767-3-4.8-3-4.8s-3 3.033-3 4.8 1.343 3.2 3 3.2 3-1.433 3-3.2Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 4v4m-8.5-.5 3 3m11 0 3-3M2 17h4m12 0h4"/></svg>`
)

export function Dashboard(props: IconProps) {
  return <Icon name={name} {...props} />
}

Dashboard.prototype.name = name
