// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'data-transfer-up/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7 4v1m0 4v1m10 10V4m0 0 3 3m-3-3-3 3m-7 7v6m0 0 3-3m-3 3-3-3"/></svg>`
)

export function DataTransferUp(props: IconProps) {
  return <Icon name={name} {...props} />
}

DataTransferUp.prototype.name = name
