// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'database-check-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M13.47 18.47a.75.75 0 0 1 1.06 0L17 20.94l4.47-4.47a.75.75 0 1 1 1.06 1.06l-5 5a.75.75 0 0 1-1.06 0l-3-3a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M15.591 17.409a2.25 2.25 0 1 0-3.182 3.182l1.021 1.02c-.713.09-1.519.139-2.43.139-3.59 0-5.547-.767-6.613-1.68-.536-.46-.825-.939-.977-1.33a2.478 2.478 0 0 1-.156-.648 1.377 1.377 0 0 1-.003-.055v-.02l-.001-.01v-.005S3.25 18 4 18h-.75v-2.25A.75.75 0 0 1 4 15c.414-.001.954.266 1.237.568a.63.63 0 0 0 .074.072c.69.493 2.256 1.11 5.689 1.11 3.433 0 4.999-.617 5.69-1.11.03-.022.059-.044.087-.067.36-.288.761-.574 1.223-.573a.75.75 0 0 1 .75.75v1.318L17 18.818l-1.409-1.41Z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M4 9a.75.75 0 0 0-.75.75V12H4c-.75 0-.75.002-.75.002v.035a1.384 1.384 0 0 0 .024.215c.021.128.061.296.136.489.152.39.441.87.977 1.329 1.066.913 3.023 1.68 6.613 1.68 3.59 0 5.547-.767 6.613-1.68.536-.46.825-.938.977-1.33a2.472 2.472 0 0 0 .156-.648 1.36 1.36 0 0 0 .003-.055v-.02l.001-.01v-.005S18.75 12 18 12h.75V9.75A.75.75 0 0 0 18 9c-.462-.001-.863.285-1.223.573a2.012 2.012 0 0 1-.088.067c-.69.493-2.256 1.11-5.689 1.11-3.433 0-4.999-.617-5.69-1.11a.634.634 0 0 1-.073-.071C4.954 9.266 4.414 8.999 4 9Z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M4.387 3.93C5.453 3.018 7.41 2.25 11 2.25c3.59 0 5.547.767 6.613 1.68.536.46.825.939.977 1.33a2.474 2.474 0 0 1 .156.648 1.178 1.178 0 0 1-.02.344 2.474 2.474 0 0 1-.136.489c-.152.39-.441.87-.977 1.328C16.547 8.983 14.59 9.75 11 9.75c-3.59 0-5.547-.767-6.613-1.68-.536-.46-.825-.939-.977-1.33a2.478 2.478 0 0 1-.136-.488 1.436 1.436 0 0 1-.024-.256c0-.083.01-.166.024-.248.021-.128.061-.295.136-.489.152-.39.441-.87.977-1.328Z" clip-rule="evenodd"/></svg>`
)

export function DatabaseCheckSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

DatabaseCheckSolid.prototype.name = name
