// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'database-xmark/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m17.121 21.364 2.122-2.121m2.121-2.122-2.121 2.122m0 0L17.12 17.12m2.122 2.122 2.121 2.121M4 6v6s0 3 7 3 7-3 7-3V6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 3c7 0 7 3 7 3s0 3-7 3-7-3-7-3 0-3 7-3Zm0 18c-7 0-7-3-7-3v-6"/></svg>`
)

export function DatabaseXmark(props: IconProps) {
  return <Icon name={name} {...props} />
}

DatabaseXmark.prototype.name = name
