// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'design-pencil/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M8 21.168V14l4-7 4 7v7.168"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M8 14s1.127 1 2 1 2-1 2-1 1.127 1 2 1 2-1 2-1"/></svg>`
)

export function DesignPencil(props: IconProps) {
  return <Icon name={name} {...props} />
}

DesignPencil.prototype.name = name
