// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'dev-mode-laptop/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M3.2 14.222V4a2 2 0 0 1 2-2h13.6a2 2 0 0 1 2 2v10.222m-17.6 0h17.6m-17.6 0-1.48 5.234A2 2 0 0 0 3.644 22h16.712a2 2 0 0 0 1.924-2.544l-1.48-5.234"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 19h2m1-13 2 2-2 2m-4-4L8 8l2 2"/></svg>`
)

export function DevModeLaptop(props: IconProps) {
  return <Icon name={name} {...props} />
}

DevModeLaptop.prototype.name = name
