// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'dice-three/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M3 20.4V3.6a.6.6 0 0 1 .6-.6h16.8a.6.6 0 0 1 .6.6v16.8a.6.6 0 0 1-.6.6H3.6a.6.6 0 0 1-.6-.6Z"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7.5 8a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1Zm4.5 4.5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1Zm4.5 4.5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1Z"/></svg>`
)

export function DiceThree(props: IconProps) {
  return <Icon name={name} {...props} />
}

DiceThree.prototype.name = name
