// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'divide/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 21v-9a5 5 0 0 0-5-5H3m9 14v-9a5 5 0 0 1 5-5h4"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7 3 3 7l4 4m10-8 4 4-4 4"/></svg>`
)

export function Divide(props: IconProps) {
  return <Icon name={name} {...props} />
}

Divide.prototype.name = name
