// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'double-check/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" d="m1.5 12.5 4.076 4.076a.6.6 0 0 0 .848 0L9 14m7-7-4 4"/><path stroke="currentColor" stroke-linecap="round" d="m7 12 4.576 4.576a.6.6 0 0 0 .848 0L22 7"/></svg>`
)

export function DoubleCheck(props: IconProps) {
  return <Icon name={name} {...props} />
}

DoubleCheck.prototype.name = name
