// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'drag/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 12 4 4m0 0v4m0-4h4m4 8 8-8m0 0v4m0-4h-4m-4 8-8 8m0 0v-4m0 4h4m4-8 8 8m0 0v-4m0 4h-4"/></svg>`
)

export function Drag(props: IconProps) {
  return <Icon name={name} {...props} />
}

Drag.prototype.name = name
