// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'emoji-satisfied/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M10 9H8m8 0h-2M2 12c0 5.523 4.477 10 10 10s10-4.477 10-10S17.523 2 12 2 2 6.477 2 12Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16.5 14.5s-1.5 2-4.5 2-4.5-2-4.5-2"/></svg>`
)

export function EmojiSatisfied(props: IconProps) {
  return <Icon name={name} {...props} />
}

EmojiSatisfied.prototype.name = name
