// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'enlarge-round-arrow/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M8.5 9.5 6 12l2.5 2.5m7-5L18 12l-2.5 2.5"/><path stroke="currentColor" d="M2 15V9a4 4 0 0 1 4-4h12a4 4 0 0 1 4 4v6a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4Z"/></svg>`
)

export function EnlargeRoundArrow(props: IconProps) {
  return <Icon name={name} {...props} />
}

EnlargeRoundArrow.prototype.name = name
