// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'ev-station/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 5v4"/><path stroke="currentColor" d="M5 19V9a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2Z"/><path stroke="currentColor" d="M5 10V5a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11.167 11 9.5 14h4l-1.667 3"/></svg>`
)

export function EvStation(props: IconProps) {
  return <Icon name={name} {...props} />
}

EvStation.prototype.name = name
