// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'facetime-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M1.25 8A6.75 6.75 0 0 1 8 1.25h8A6.75 6.75 0 0 1 22.75 8v8A6.75 6.75 0 0 1 16 22.75H8A6.75 6.75 0 0 1 1.25 16V8Zm4 3A2.75 2.75 0 0 1 8 8.25h3a2.75 2.75 0 0 1 2.74 2.508l2.85-2.138c.89-.667 2.16-.032 2.16 1.08v4.6c0 1.112-1.27 1.748-2.16 1.08l-2.85-2.138A2.75 2.75 0 0 1 11 15.75H8A2.75 2.75 0 0 1 5.25 13v-2Z" clip-rule="evenodd"/></svg>`
)

export function FacetimeSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

FacetimeSolid.prototype.name = name
