// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'fishing/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0 0v10c0 6-10 6-10 0v-4l2 2"/></svg>`
)

export function Fishing(props: IconProps) {
  return <Icon name={name} {...props} />
}

Fishing.prototype.name = name
