// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'flip-reverse/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9.5 12v2m-3.75-2-.938 2m2.813 6H9.5v-2m-5.625 2H2l.938-2M7.625 8 9.5 4v4m5 12H22L14.5 4v16Z"/></svg>`
)

export function FlipReverse(props: IconProps) {
  return <Icon name={name} {...props} />
}

FlipReverse.prototype.name = name
