// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'forward-15-seconds/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 13a9 9 0 1 1-9-9m0 0h7.5m0 0-2-2m2 2-2 2M9 9v7"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 9h-2a1 1 0 0 0-1 1v1.5a1 1 0 0 0 1 1h1a1 1 0 0 1 1 1V15a1 1 0 0 1-1 1h-2"/></svg>`
)

export function Forward15Seconds(props: IconProps) {
  return <Icon name={name} {...props} />
}

Forward15Seconds.prototype.name = name
