// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'git-branch/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM6 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0-4V3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M8 18h1c3.5 0 9-2.1 9-8.5V8"/></svg>`
)

export function GitBranch(props: IconProps) {
  return <Icon name={name} {...props} />
}

GitBranch.prototype.name = name
