// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'git-merge/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM6 21V7"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 7v2c0 3.5 2.5 9 8.5 9H16M6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>`
)

export function GitMerge(props: IconProps) {
  return <Icon name={name} {...props} />
}

GitMerge.prototype.name = name
