// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'hand-cash/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m2 11 2.807-3.157A4 4 0 0 1 7.797 6.5H8m-6 13h5.5l4-3s.81-.547 2-1.5c2.5-2 0-5.166-2.5-3.5C8.964 12.857 7 14 7 14"/><path stroke="currentColor" d="M8 13.5V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-6.5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 12a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm4.5-1.99.01-.011m-9.01.011.01-.011"/></svg>`
)

export function HandCash(props: IconProps) {
  return <Icon name={name} {...props} />
}

HandCash.prototype.name = name
