// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'heart-arrow-down/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m5.478 14.883-1.824-1.89c-2.205-2.286-2.205-5.976 0-8.261a5.58 5.58 0 0 1 8.08 0l.266.274.265-.274A5.612 5.612 0 0 1 16.305 3c1.52 0 2.973.624 4.04 1.732A5.95 5.95 0 0 1 22 8.862a5.95 5.95 0 0 1-1.654 4.13c-.603.626-1.202 1.258-1.8 1.891M12 21.5V11m4 6.5-4 4-4-4"/></svg>`
)

export function HeartArrowDown(props: IconProps) {
  return <Icon name={name} {...props} />
}

HeartArrowDown.prototype.name = name
