// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'help-square-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M2.25 3.6c0-.746.604-1.35 1.35-1.35h16.8c.746 0 1.35.604 1.35 1.35v16.8a1.35 1.35 0 0 1-1.35 1.35H3.6a1.35 1.35 0 0 1-1.35-1.35V3.6Zm8.095 4.003C10 7.895 9.75 8.341 9.75 9a.75.75 0 0 1-1.5 0c0-1.091.437-1.958 1.124-2.54.67-.57 1.538-.835 2.376-.835.838 0 1.705.265 2.376.834.687.583 1.124 1.45 1.124 2.541 0 .766-.196 1.35-.517 1.83-.269.404-.619.716-.894.962l-.087.078c-.308.276-.539.504-.709.804-.162.287-.293.688-.293 1.326a.75.75 0 1 1-1.5 0c0-.862.181-1.524.488-2.065.299-.528.693-.894 1.01-1.18l.072-.065c.3-.27.508-.455.665-.692.149-.222.265-.514.265-.998 0-.659-.25-1.105-.595-1.397-.36-.306-.868-.478-1.405-.478s-1.045.172-1.405.478Zm2.223 10.898a.75.75 0 0 0-1.115-1.004l-.01.011a.75.75 0 0 0 1.114 1.004l.01-.011Z" clip-rule="evenodd"/></svg>`
)

export function HelpSquareSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

HelpSquareSolid.prototype.name = name
