// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'input-output/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" d="M14 19a7 7 0 1 0 0-14 7 7 0 0 0 0 14Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 19V5"/></svg>`
)

export function InputOutput(props: IconProps) {
  return <Icon name={name} {...props} />
}

InputOutput.prototype.name = name
