// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'keyframes-plus/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 12h3m3 0H5m0 0V9m0 3v3m1.25-9 .245-.28a2 2 0 0 1 3.01 0l4.343 4.963a2 2 0 0 1 0 2.634L9.505 18.28a2 2 0 0 1-3.01 0L6.25 18"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m13 19 4.884-5.698a2 2 0 0 0 0-2.604L13 5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m17 19 4.884-5.698a2 2 0 0 0 0-2.604L17 5"/></svg>`
)

export function KeyframesPlus(props: IconProps) {
  return <Icon name={name} {...props} />
}

KeyframesPlus.prototype.name = name
