// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'learning/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.818 22v-2.857C6.52 16.166 3 14.572 3 10c0-4.57 2.727-8.056 8.182-8 3.927.042 7.636 2.286 7.636 6.858L21 12.286c0 2.286-2.182 2.286-2.182 2.286s.546 5.714-4.364 5.714V22"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 12a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/><path stroke="currentColor" stroke-dasharray="0.3 2" stroke-linecap="round" stroke-linejoin="round" d="M11 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/></svg>`
)

export function Learning(props: IconProps) {
  return <Icon name={name} {...props} />
}

Learning.prototype.name = name
