// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'loft-3d/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 17c-9 0-11 6-20 6M22 1C13 1 11 7 2 7m10 9.5v-9m0 9 2.5-2.5M12 16.5 9.5 14M12 7.5l2.5 2.5M12 7.5 9.5 10"/></svg>`
)

export function Loft3D(props: IconProps) {
  return <Icon name={name} {...props} />
}

Loft3D.prototype.name = name
