// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'long-arrow-down-left/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m10.25 19.25-3.5-3.5 3.5-3.5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75h6a4 4 0 0 0 4-4v-7"/></svg>`
)

export function LongArrowDownLeft(props: IconProps) {
  return <Icon name={name} {...props} />
}

LongArrowDownLeft.prototype.name = name
