// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'long-arrow-down-right/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m13.25 19.25 3.5-3.5-3.5-3.5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16.75 15.75h-6a4 4 0 0 1-4-4v-7"/></svg>`
)

export function LongArrowDownRight(props: IconProps) {
  return <Icon name={name} {...props} />
}

LongArrowDownRight.prototype.name = name
