// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'magnet-energy/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 9v6.74C5 19.199 8.134 22 12 22s7-2.802 7-6.26V9M5 9h3m8 0h3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14.074 11.5v3.56c0 1.072-.928 1.94-2.074 1.94s-2.074-.868-2.074-1.94V11.5"/><path stroke="currentColor" stroke-linejoin="round" d="M10 13H5m14 0h-5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11.667 2 10 5h4l-1.667 3"/></svg>`
)

export function MagnetEnergy(props: IconProps) {
  return <Icon name={name} {...props} />
}

MagnetEnergy.prototype.name = name
