// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'mail-open/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m7 12 5 3.5 5-3.5"/><path stroke="currentColor" d="M2 20V9.132a2 2 0 0 1 .971-1.715l8-4.8a2 2 0 0 1 2.058 0l8 4.8A2 2 0 0 1 22 9.132V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2Z"/></svg>`
)

export function MailOpen(props: IconProps) {
  return <Icon name={name} {...props} />
}

MailOpen.prototype.name = name
