// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'microphone-minus/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16.992 19h6"/><rect width="6" height="12" x="5" y="2" stroke="currentColor" rx="3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M1 10v1a7 7 0 0 0 7 7v0a7 7 0 0 0 7-7v-1m-7 8v4m0 0H5m3 0h3"/></svg>`
)

export function MicrophoneMinus(props: IconProps) {
  return <Icon name={name} {...props} />
}

MicrophoneMinus.prototype.name = name
