// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'microphone-warning/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 14v4m0 4.01.01-.011"/><rect width="6" height="12" x="7" y="2" stroke="currentColor" rx="3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 10v1a7 7 0 0 0 7 7v0a7 7 0 0 0 7-7v-1m-7 8v4m0 0H7m3 0h3"/></svg>`
)

export function MicrophoneWarning(props: IconProps) {
  return <Icon name={name} {...props} />
}

MicrophoneWarning.prototype.name = name
