// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'more-horiz/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 12.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm-8 0a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm-8 0a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z"/></svg>`
)

export function MoreHoriz(props: IconProps) {
  return <Icon name={name} {...props} />
}

MoreHoriz.prototype.name = name
