// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'move-down/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 6a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm0 3v13m0 0 3-3m-3 3-3-3"/></svg>`
)

export function MoveDown(props: IconProps) {
  return <Icon name={name} {...props} />
}

MoveDown.prototype.name = name
