// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'move-left/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 14a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm-5-2H2m0 0 3-3m-3 3 3 3"/></svg>`
)

export function MoveLeft(props: IconProps) {
  return <Icon name={name} {...props} />
}

MoveLeft.prototype.name = name
