// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'multiple-pages-plus/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M1.992 19h3m3 0h-3m0 0v-3m0 3v3M7 2h9.5L21 6.5V19"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11 22h5.5a1.5 1.5 0 0 0 1.5-1.5V8.749a.6.6 0 0 0-.176-.425l-3.148-3.148A.6.6 0 0 0 14.25 5H4.5A1.5 1.5 0 0 0 3 6.5V13"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 5v3.4a.6.6 0 0 0 .6.6H18"/></svg>`
)

export function MultiplePagesPlus(props: IconProps) {
  return <Icon name={name} {...props} />
}

MultiplePagesPlus.prototype.name = name
