// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'network-right-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(0 -1 -1 0 22 21)"/><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(0 -1 -1 0 7 15.5)"/><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(0 -1 -1 0 22 10)"/><path stroke="currentColor" stroke-width="1.5" d="M17 17.5h-3.5a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2H17M11.5 12H7"/></svg>`
)

export function NetworkRightSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

NetworkRightSolid.prototype.name = name
