// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'network-reverse-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(1 0 0 -1 3 22)"/><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(1 0 0 -1 8.5 7)"/><rect width="7" height="5" fill="currentColor" stroke="currentColor" stroke-width="1.5" rx=".6" transform="matrix(1 0 0 -1 14 22)"/><path stroke="currentColor" stroke-width="1.5" d="M6.5 17v-3.5a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2V17M12 11.5V7"/></svg>`
)

export function NetworkReverseSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

NetworkReverseSolid.prototype.name = name
