// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'non-binary/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 9a6 6 0 1 1 0 12 6 6 0 0 1 0-12Zm0 0V3M9 4l6 3m0-3L9 7"/></svg>`
)

export function NonBinary(props: IconProps) {
  return <Icon name={name} {...props} />
}

NonBinary.prototype.name = name
