// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'number-3-square-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M2.25 3.6c0-.746.604-1.35 1.35-1.35h16.8c.746 0 1.35.604 1.35 1.35v16.8a1.35 1.35 0 0 1-1.35 1.35H3.6a1.35 1.35 0 0 1-1.35-1.35V3.6ZM12 8.75c1.131 0 1.75.707 1.75 1.25 0 .42-.117.722-.288.911-.16.177-.442.339-.962.339a.75.75 0 0 0 0 1.5c.52 0 .802.162.962.339.17.19.288.492.288.911 0 .543-.619 1.25-1.75 1.25s-1.75-.707-1.75-1.25a.75.75 0 0 0-1.5 0c0 1.666 1.62 2.75 3.25 2.75s3.25-1.084 3.25-2.75c0-.685-.193-1.383-.676-1.917a2.452 2.452 0 0 0-.079-.083 2.36 2.36 0 0 0 .079-.083c.483-.534.676-1.232.676-1.917 0-1.666-1.62-2.75-3.25-2.75S8.75 8.334 8.75 10a.75.75 0 0 0 1.5 0c0-.543.619-1.25 1.75-1.25Z" clip-rule="evenodd"/></svg>`
)

export function Number3SquareSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

Number3SquareSolid.prototype.name = name
