// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'number-3-square/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M3 20.4V3.6a.6.6 0 0 1 .6-.6h16.8a.6.6 0 0 1 .6.6v16.8a.6.6 0 0 1-.6.6H3.6a.6.6 0 0 1-.6-.6Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9.5 10c0-1.105 1.12-2 2.5-2s2.5.895 2.5 2-.62 2-2 2m-3 2c0 1.105 1.12 2 2.5 2s2.5-.895 2.5-2-.62-2-2-2"/></svg>`
)

export function Number3Square(props: IconProps) {
  return <Icon name={name} {...props} />
}

Number3Square.prototype.name = name
