// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'number-7-square-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M3.6 2.25A1.35 1.35 0 0 0 2.25 3.6v16.8c0 .746.604 1.35 1.35 1.35h16.8a1.35 1.35 0 0 0 1.35-1.35V3.6a1.35 1.35 0 0 0-1.35-1.35H3.6Zm5.9 5a.75.75 0 0 0 0 1.5h3.35c-.3.378-.637.828-.974 1.334C10.851 11.621 9.75 13.774 9.75 16a.75.75 0 0 0 1.5 0c0-1.775.899-3.621 1.874-5.084a18.4 18.4 0 0 1 1.752-2.225l.118-.124.03-.03.006-.006a.75.75 0 0 0-.53-1.281h-5Z" clip-rule="evenodd"/></svg>`
)

export function Number7SquareSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

Number7SquareSolid.prototype.name = name
