// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'okrs/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0-7a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM3 5h10M3 12h10M3 19h10m3 2.243 2.121-2.122m0 0L20.243 17m-2.122 2.121L16 17m2.121 2.121 2.122 2.122"/></svg>`
)

export function Okrs(props: IconProps) {
  return <Icon name={name} {...props} />
}

Okrs.prototype.name = name
