// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'on-tag/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M1 15V9a6 6 0 0 1 6-6h10a6 6 0 0 1 6 6v6a6 6 0 0 1-6 6H7a6 6 0 0 1-6-6Z"/><path stroke="currentColor" d="M9 9a3 3 0 1 1 0 6 3 3 0 0 1 0-6Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 15V9l4 6V9"/></svg>`
)

export function OnTag(props: IconProps) {
  return <Icon name={name} {...props} />
}

OnTag.prototype.name = name
