// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'orange-slice-alt/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M13.39 10.11 5.61 2.334c-4.295 4.296-4.295 11.26 0 15.556 4.296 4.296 11.26 4.296 15.557 0l-7.778-7.778Zm0 0 .353 8.133m-.354-8.132H5.612m7.779 0-5.304 5.303"/></svg>`
)

export function OrangeSliceAlt(props: IconProps) {
  return <Icon name={name} {...props} />
}

OrangeSliceAlt.prototype.name = name
