// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'orange-slice/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m10.613 10.11 7.778-7.777c4.295 4.296 4.295 11.26 0 15.556-4.296 4.296-11.261 4.296-15.557 0l7.779-7.778Zm0 0-.354 8.133m.354-8.132h7.778m-7.778 0 5.303 5.303"/></svg>`
)

export function OrangeSlice(props: IconProps) {
  return <Icon name={name} {...props} />
}

OrangeSlice.prototype.name = name
