// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'page-search/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 12V5.749a.6.6 0 0 0-.176-.425l-3.148-3.148A.6.6 0 0 0 16.252 2H4.6a.6.6 0 0 0-.6.6v18.8a.6.6 0 0 0 .6.6H11M8 10h8M8 6h4m-4 8h3m9.5 6.5L22 22"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 18a3 3 0 1 0 6 0 3 3 0 0 0-6 0Zm1-16v3.4a.6.6 0 0 0 .6.6H20"/></svg>`
)

export function PageSearch(props: IconProps) {
  return <Icon name={name} {...props} />
}

PageSearch.prototype.name = name
