// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'pin-slash-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.5 14.5 3 21"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m5 9.485 9.193 9.193 1.697-1.698-.102-.98-8.112-8.11-.979-.102L5 9.485Zm10.157-6.813 5.85 5.85-4.308 3.653L11.485 7l3.672-4.328Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m3 3 18 18"/></svg>`
)

export function PinSlashSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

PinSlashSolid.prototype.name = name
