// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'podcast/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 19a9.985 9.985 0 0 1-4-8C2 5.477 6.477 1 12 1s10 4.477 10 10a9.985 9.985 0 0 1-4 8"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 19a9.985 9.985 0 0 1-4-8C2 5.477 6.477 1 12 1s10 4.477 10 10a9.985 9.985 0 0 1-4 8"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M7.528 15a6 6 0 1 1 8.944 0"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 13a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm-1.924 3.283.815-.543a2 2 0 0 1 2.218 0l.815.543a2 2 0 0 1 .863 1.993l-.509 3.053A2 2 0 0 1 12.306 23h-.612a2 2 0 0 1-1.973-1.671l-.508-3.053a2 2 0 0 1 .863-1.993Z"/></svg>`
)

export function Podcast(props: IconProps) {
  return <Icon name={name} {...props} />
}

Podcast.prototype.name = name
