// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'polar-sh/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22c-2.21 0-4-4.477-4-10S9.79 2 12 2s4 4.477 4 10-1.79 10-4 10Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9 21c-3-1-4-5.389-4-8.5 0-3.111 1.5-7 5-9.5m5 0c3 1 4 5.389 4 8.5 0 3.111-1.5 7-5 9.5"/></svg>`
)

export function PolarSh(props: IconProps) {
  return <Icon name={name} {...props} />
}

PolarSh.prototype.name = name
