// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'redo-action/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19 5v6m-3.5-3H9s0 0 0 0-5 0-5 4.706C4 18 9 18 9 18h8.714"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12.5 11.5 16 8l-3.5-3.5"/></svg>`
)

export function RedoAction(props: IconProps) {
  return <Icon name={name} {...props} />
}

RedoAction.prototype.name = name
