// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'redo-circle-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12Zm16.321-.89a.76.76 0 0 1-.05.055l-3.5 3.375a.75.75 0 1 1-1.042-1.08l2.163-2.085H9.789a2.454 2.454 0 0 0-.308.035 2.49 2.49 0 0 0-.737.25 1.744 1.744 0 0 0-.672.624c-.178.288-.322.71-.322 1.341 0 1.438.567 2.032 1.029 2.312a2.253 2.253 0 0 0 1.014.313h.807a.75.75 0 0 1 0 1.5h-.8a3.72 3.72 0 0 1-1.798-.53c-.933-.565-1.752-1.658-1.752-3.595 0-.87.202-1.572.545-2.128.341-.554.796-.92 1.238-1.157A4.007 4.007 0 0 1 9.8 9.875h5.433L12.96 7.521a.75.75 0 0 1 1.08-1.042l3.498 3.623a.748.748 0 0 1 .033 1.009Z" clip-rule="evenodd"/></svg>`
)

export function RedoCircleSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

RedoCircleSolid.prototype.name = name
