// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'reduce/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m4 20 5-5m0 0v4m0-4H5M20 4l-5 5m0 0V5m0 4h4"/></svg>`
)

export function Reduce(props: IconProps) {
  return <Icon name={name} {...props} />
}

Reduce.prototype.name = name
