// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'repeat/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 17H8c-1.667 0-5-1-5-5s3.333-5 5-5h8c1.667 0 5 1 5 5 0 1.494-.465 2.57-1.135 3.331"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14.5 14.5 17 17l-2.5 2.5"/></svg>`
)

export function Repeat(props: IconProps) {
  return <Icon name={name} {...props} />
}

Repeat.prototype.name = name
