// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'restart/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.677 20.567C2.531 18.021.758 12.758 2.717 8.144 4.875 3.06 10.745.688 15.829 2.846c5.084 2.158 7.456 8.029 5.298 13.113a9.954 9.954 0 0 1-3.962 4.608"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 16v4.4a.6.6 0 0 0 .6.6H22m-10 1.01.01-.011"/></svg>`
)

export function Restart(props: IconProps) {
  return <Icon name={name} {...props} />
}

Restart.prototype.name = name
