// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'rhombus-arrow-right/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><g stroke="currentColor" stroke-linejoin="round" clip-path="url(#a)"><path stroke-linecap="round" d="M16 11h-6c-1 0-2 1-2 2v1m8-3-2-2m2 2-2 2"/><path d="M1.424 11.576 11.576 1.424a.6.6 0 0 1 .848 0l10.152 10.152a.6.6 0 0 1 0 .848L12.424 22.576a.6.6 0 0 1-.848 0L1.424 12.424a.6.6 0 0 1 0-.848Z"/></g><defs><clipPath id="a"><path fill="#fff" d="M0 0h24v24H0z"/></clipPath></defs></svg>`
)

export function RhombusArrowRight(props: IconProps) {
  return <Icon name={name} {...props} />
}

RhombusArrowRight.prototype.name = name
