// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sandals/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 7s.5-4-4-4-4 4-4 4m8 0h-8m8 0-.214 3M14 7l.214 3m7.572 0-.587 8.214A3 3 0 0 1 18.207 21h-.414a3 3 0 0 1-2.992-2.786L14.214 10m7.572 0h-7.572M10 7s.5-4-4-4-4 4-4 4m8 0H2m8 0-.214 3M2 7l.214 3m7.572 0-.587 8.214A3 3 0 0 1 6.207 21h-.414a3 3 0 0 1-2.992-2.786L2.214 10m7.572 0H2.214"/></svg>`
)

export function Sandals(props: IconProps) {
  return <Icon name={name} {...props} />
}

Sandals.prototype.name = name
