// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'security-pass/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m9 11 3 3 8-8"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 12a8 8 0 1 1-5.3-7.533"/></svg>`
)

export function SecurityPass(props: IconProps) {
  return <Icon name={name} {...props} />
}

SecurityPass.prototype.name = name
