// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sidebar-expand/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2Zm-9.5 0V3"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m5.5 10 1.75 2-1.75 2"/></svg>`
)

export function SidebarExpand(props: IconProps) {
  return <Icon name={name} {...props} />
}

SidebarExpand.prototype.name = name
