// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sigma-function/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 4h16v3M4 20h16v-3M4 20l8-8-8-8"/></svg>`
)

export function SigmaFunction(props: IconProps) {
  return <Icon name={name} {...props} />
}

SigmaFunction.prototype.name = name
