// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'single-tap-gesture/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 20.5a7 7 0 1 0 0-14 7 7 0 0 0 0 14Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 7.29C5.496 5.039 8.517 3.5 12 3.5c3.483 0 6.504 1.539 8 3.79"/></svg>`
)

export function SingleTapGesture(props: IconProps) {
  return <Icon name={name} {...props} />
}

SingleTapGesture.prototype.name = name
