// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sort/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M10 14H2m6-4H2m4-4H2m10 12H2m17 2V4m0 16 3-3m-3 3-3-3m3-13 3 3m-3-3-3 3"/></svg>`
)

export function Sort(props: IconProps) {
  return <Icon name={name} {...props} />
}

Sort.prototype.name = name
