// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sound-min-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M14.537 3.396c1.163-.767 2.713.068 2.713 1.461v14.286c0 1.394-1.55 2.228-2.713 1.461l-6-3.955a.25.25 0 0 0-.137-.042H5.5a2.75 2.75 0 0 1-2.75-2.75v-3.714a2.75 2.75 0 0 1 2.75-2.75h2.9a.25.25 0 0 0 .138-.041l5.999-3.956ZM20.5 8.25a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd"/></svg>`
)

export function SoundMinSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

SoundMinSolid.prototype.name = name
