// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'split-area/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 20H4v-4h16v4ZM2 12h20M7 4H4v3m7-3h2m4 0h3v3"/></svg>`
)

export function SplitArea(props: IconProps) {
  return <Icon name={name} {...props} />
}

SplitArea.prototype.name = name
