// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'square-wave/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 12h3V4h6v16h6v-8h3m-6.5 0h1m-7 0h1"/></svg>`
)

export function SquareWave(props: IconProps) {
  return <Icon name={name} {...props} />
}

SquareWave.prototype.name = name
