// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'square-3d-three-points/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" d="M3 21V3.6a.6.6 0 0 1 .6-.6H21"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 21h3.4a.6.6 0 0 0 .6-.6V17m0-10v2m0 3v2M7 21h2m3 0h2"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm0 18a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM21 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/></svg>`
)

export function Square3DThreePoints(props: IconProps) {
  return <Icon name={name} {...props} />
}

Square3DThreePoints.prototype.name = name
