// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'strategy/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 20.5C7 11 11.5 8 20 6"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m15.909 3.81 4.486 2.09-2.092 4.486M5 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm11 13.243 2.121-2.122m0 0L20.243 16m-2.122 2.121L16 16m2.121 2.121 2.122 2.122"/></svg>`
)

export function Strategy(props: IconProps) {
  return <Icon name={name} {...props} />
}

Strategy.prototype.name = name
