// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'stretching/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM5 20l4.91-.524 2.726-5.238L13.727 9l-4.909 1.048 1.636 2.095m4.364 3.143H17V20"/></svg>`
)

export function Stretching(props: IconProps) {
  return <Icon name={name} {...props} />
}

Stretching.prototype.name = name
