// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = '3d-arc/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M22 16c0-5.523-4.477-10-10-10S2 10.477 2 16"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm20 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/></svg>`
)

export function Svg3DArc(props: IconProps) {
  return <Icon name={name} {...props} />
}

Svg3DArc.prototype.name = name
