// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = '3d-ellipse/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 22c4.418 0 8-4.477 8-10S16.418 2 12 2 4 6.477 4 12s3.582 10 8 10Z"/><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 23a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/></svg>`
)

export function Svg3DEllipse(props: IconProps) {
  return <Icon name={name} {...props} />
}

Svg3DEllipse.prototype.name = name
