// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'swipe-down-gesture/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 14a6 6 0 1 0 0-12 6 6 0 0 0 0 12Zm0 0v8m0 0-3-3m3 3 3-3"/></svg>`
)

export function SwipeDownGesture(props: IconProps) {
  return <Icon name={name} {...props} />
}

SwipeDownGesture.prototype.name = name
