// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'temperature-down/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 12a5 5 0 1 0 6 0m-6 0V3h6v9m0-9h2m-2 3h2m-2 3h2"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M8 14a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm0 0V6m11 0v12m0 0 2.5-2.5M19 18l-2.5-2.5"/></svg>`
)

export function TemperatureDown(props: IconProps) {
  return <Icon name={name} {...props} />
}

TemperatureDown.prototype.name = name
