// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'test-tube/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6.141 19.995c2.458 1.72 4.281-.012 5.318-1.492l7.3-10.426 1.966-1.065-6.553-4.588-8.447 12.064c-1.037 1.48-2.041 3.786.416 5.507Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16.091 11.02c-2.876-.853-4.403.781-7.28-.071"/></svg>`
)

export function TestTube(props: IconProps) {
  return <Icon name={name} {...props} />
}

TestTube.prototype.name = name
