// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'text-magnifying-glass/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19.5 19.5 21 21m-7-4a3 3 0 1 0 6 0 3 3 0 0 0-6 0ZM9 5v12m0 0H7m2 0h2m4-10V5H3v2"/></svg>`
)

export function TextMagnifyingGlass(props: IconProps) {
  return <Icon name={name} {...props} />
}

TextMagnifyingGlass.prototype.name = name
