// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'tournament/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 3h5v6H3m5-3h7v12H8m7-6h7M3 15h5v6H3"/></svg>`
)

export function Tournament(props: IconProps) {
  return <Icon name={name} {...props} />
}

Tournament.prototype.name = name
