// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'tram/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m15 16.01.01-.011M9 16.01l.01-.011M13 6h2a5 5 0 0 1 5 5v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-7a5 5 0 0 1 5-5h4Zm0 0 1-4m0 0h3m-3 0H7"/><path stroke="currentColor" stroke-linecap="round" d="m10.5 20-2 2.5m5-2.5 2 2.5m1-2.5 2 2.5M7.5 20l-2 2.5"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9.609 9h4.782A2.609 2.609 0 0 1 17 11.609a.391.391 0 0 1-.391.391H7.39a.391.391 0 0 1-.39-.391A2.609 2.609 0 0 1 9.609 9Z"/></svg>`
)

export function Tram(props: IconProps) {
  return <Icon name={name} {...props} />
}

Tram.prototype.name = name
