// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'transition-down-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M2.25 5A3.75 3.75 0 0 1 6 1.25h12A3.75 3.75 0 0 1 21.75 5v2A3.75 3.75 0 0 1 18 10.75H6A3.75 3.75 0 0 1 2.25 7V5ZM3 15.25a.75.75 0 0 1 .75.75v2A3.25 3.25 0 0 0 7 21.25h10A3.25 3.25 0 0 0 20.25 18v-2a.75.75 0 0 1 1.5 0v2A4.75 4.75 0 0 1 17 22.75H7A4.75 4.75 0 0 1 2.25 18v-2a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M12 9.25a.75.75 0 0 1 .75.75v6.19l1.72-1.72a.75.75 0 1 1 1.06 1.06l-3 3a.75.75 0 0 1-1.06 0l-3-3a.75.75 0 1 1 1.06-1.06l1.72 1.72V10a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd"/></svg>`
)

export function TransitionDownSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

TransitionDownSolid.prototype.name = name
