// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'tunnel/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 20 3 14"/><path stroke="currentColor" stroke-linecap="round" d="M16 10v1m-4-2v1M8 8v1"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M3 21h18v-9a9 9 0 1 0-18 0v9Z"/></svg>`
)

export function Tunnel(props: IconProps) {
  return <Icon name={name} {...props} />
}

Tunnel.prototype.name = name
