// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'undo-action/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 5v6m3.5-3H15s0 0 0 0 5 0 5 4.706C20 18 15 18 15 18H6.286"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M11.5 11.5 8 8l3.5-3.5"/></svg>`
)

export function UndoAction(props: IconProps) {
  return <Icon name={name} {...props} />
}

UndoAction.prototype.name = name
