// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'union-alt/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M9 22A7 7 0 1 0 9 8a7 7 0 0 0 0 14Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 16a7 7 0 1 0 0-14 7 7 0 0 0 0 14Z"/></svg>`
)

export function UnionAlt(props: IconProps) {
  return <Icon name={name} {...props} />
}

UnionAlt.prototype.name = name
