// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'usb/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12.5 2v15m0-3 5.5-2V8.5M12.5 16 7 14.5v-3M12.5 22a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm4-16.5v3h3v-3h-3Zm-6-1.5 2-2 2 2M7 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>`
)

export function Usb(props: IconProps) {
  return <Icon name={name} {...props} />
}

Usb.prototype.name = name
