// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'video-projector/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 19h2m12 0h2"/><path stroke="currentColor" d="M2 16.4V7.6a.6.6 0 0 1 .6-.6h18.8a.6.6 0 0 1 .6.6v8.8a.6.6 0 0 1-.6.6H2.6a.6.6 0 0 1-.6-.6Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m5 10.01.01-.011M8 10.01l.01-.011m2.99.011.01-.011M5 14.01l.01-.011M8 14.01l.01-.011m2.99.011.01-.011M17 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>`
)

export function VideoProjector(props: IconProps) {
  return <Icon name={name} {...props} />
}

VideoProjector.prototype.name = name
