// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'voice-check/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 3v16M8 8v6m12-5v4M4 9v4m12-7v9m-.5 4.5 2 2 5-5"/></svg>`
)

export function VoiceCheck(props: IconProps) {
  return <Icon name={name} {...props} />
}

VoiceCheck.prototype.name = name
