// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'web-window-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4.222 3.25c-1.661 0-2.972 1.38-2.972 3.036v11.428c0 1.657 1.31 3.036 2.972 3.036h15.556c1.661 0 2.972-1.38 2.972-3.036V6.286c0-1.657-1.31-3.036-2.972-3.036H4.222Zm.778 3a.75.75 0 0 0 0 1.5h1a.75.75 0 0 0 0-1.5H5Z" clip-rule="evenodd"/></svg>`
)

export function WebWindowSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

WebWindowSolid.prototype.name = name
