// This file is automatically generated. Modifying its content manually is discouraged.
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'web-window-energy-consumption-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M1.25 6.286c0-1.657 1.31-3.036 2.972-3.036h15.556c1.661 0 2.972 1.38 2.972 3.036v11.428c0 1.657-1.31 3.036-2.972 3.036H4.222c-1.661 0-2.972-1.38-2.972-3.036V6.286Zm3 .714A.75.75 0 0 1 5 6.25h1a.75.75 0 0 1 0 1.5H5A.75.75 0 0 1 4.25 7Zm8.072 2.364a.75.75 0 1 0-1.31-.728l-1.668 3A.75.75 0 0 0 10 12.75h2.725l-1.047 1.886a.75.75 0 0 0 1.31.728l1.668-3A.75.75 0 0 0 14 11.25h-2.725l1.047-1.886Z" clip-rule="evenodd"/></svg>`
)

export function WebWindowEnergyConsumptionSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

WebWindowEnergyConsumptionSolid.prototype.name = name
