// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'wifi-tag-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M8 2.25A6.75 6.75 0 0 0 1.25 9v6A6.75 6.75 0 0 0 8 21.75h8A6.75 6.75 0 0 0 22.75 15V9A6.75 6.75 0 0 0 16 2.25H8Zm4.568 13a.75.75 0 0 0-1.115-1.003l-.01.011a.75.75 0 0 0 1.114 1.004l.01-.011Zm3.856-3.52c-2.2-2.64-6.648-2.64-8.848 0a.75.75 0 1 1-1.152-.96c2.8-3.36 8.352-3.36 11.152 0a.75.75 0 1 1-1.152.96ZM9.6 13.7a3 3 0 0 1 4.8 0 .75.75 0 1 0 1.2-.9c-1.8-2.4-5.4-2.4-7.2 0a.75.75 0 0 0 1.2.9Z" clip-rule="evenodd"/></svg>`
)

export function WifiTagSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

WifiTagSolid.prototype.name = name
