// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'wristwatch/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M16 16.472V20a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-3.528m0-8.944V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v3.528"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 12a6 6 0 1 0-12 0 6 6 0 0 0 12 0Z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14 12h-2v-2"/></svg>`
)

export function Wristwatch(props: IconProps) {
  return <Icon name={name} {...props} />
}

Wristwatch.prototype.name = name
